import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

export default StyleSheet.create({
    cruinvitebutton: {
        width: 125,
        height: 30,
        backgroundColor: COLORS.AKCRUBLUE,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 3,
        marginRight: 10,
    },
    followbutton: {
        width: '25%',
        height: 30,
        backgroundColor: COLORS.CATPURPLGT,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 3,
    },
    unfollowbutton: {
        width: 125,
        height: 30,
        backgroundColor: COLORS.CATPURPDRK,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 3,
    },
    watchlisttext: {
        ...FONTS.Title2,
        marginTop: 10,
        marginBottom: 20,
        textAlign: 'center',
        fontSize: 14,
    },
    watchlistcontainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 15,
        marginBottom: 20,
    },
    seperator: {
        borderBottomWidth: 1.5,
        borderColor: COLORS.DARKERGREY,
        marginTop: 20,
        marginBottom: 10,
        marginHorizontal: 15,
    },
    desctext: {
        ...FONTS.Title2,
        marginTop: 25,
        marginBottom: 20,
        textAlign: 'center',
        fontSize: 14,
        textDecorationLine: 'underline',
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    gallerycontainer: {
        marginHorizontal: 15,
        marginBottom: '20%',
    },

    galleryImagesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 20,
    },
    galleryImage: {
        width: SIZES.ScreenWidth / 3.55,
        height: SIZES.ScreenWidth / 2.35,
        margin: 5,
        borderRadius: 5,
    },
    selectedPhotoContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    selectedPhoto: {
        width: SIZES.ScreenWidth,
        aspectRatio: 1,
        opacity: 0,
        marginTop: -100,
    },
});
