import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

const UNIFIED_BUTTON_RADIUS = 10;

export default StyleSheet.create({
    refCardScroll: {
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 28,
    },
    refCardScrollWithPinnedFooter: {
        paddingBottom: 110,
    },
    refCard: {
        borderRadius: 24,
        borderWidth: 1.2,
        borderColor: '#AF62FF',
        paddingHorizontal: 14,
        paddingVertical: 14,
        shadowColor: '#B055FF',
        shadowOpacity: 0.5,
        shadowRadius: 14,
        elevation: 10,
    },
    refTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    refBrand: {
        ...FONTS.Title1,
        color: '#F2A4FF',
        fontSize: 32,
    },
    refFollowPill: {
        borderWidth: 1,
        borderColor: '#CB8DFF',
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: UNIFIED_BUTTON_RADIUS,
        backgroundColor: 'rgba(139, 58, 219, 0.4)',
        marginLeft: 'auto',
    },
    refFollowText: {
        ...FONTS.Title3,
        color: '#F5DCFF',
    },
    refAvatarWrap: {
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 10,
    },
    refName: {
        ...FONTS.Title1,
        textAlign: 'center',
        color: '#FFD2F5',
        marginBottom: 10,
    },
    refMetrics: {
        flexDirection: 'row',
        justifyContent: 'center',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 10,
    },
    refMetricChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 9,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    refMetricText: {
        ...FONTS.chart,
        color: COLORS.WHITE,
        marginLeft: 4,
    },
    refMetricColumn: {
        marginLeft: 6,
        alignItems: 'center',
    },
    refMetricLabel: {
        ...FONTS.chart,
        color: COLORS.LIGHTGREY,
        fontSize: 10,
        lineHeight: 12,
        textAlign: 'center',
    },
    refMetricCount: {
        ...FONTS.chart,
        color: COLORS.WHITE,
        fontSize: 12,
        lineHeight: 14,
        textAlign: 'center',
    },
    refActionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
        marginBottom: 12,
    },
    refTag: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#A15FDA',
        borderRadius: UNIFIED_BUTTON_RADIUS,
        backgroundColor: 'rgba(57, 20, 101, 0.65)',
        paddingVertical: 7,
    },
    refTagText: {
        ...FONTS.Title3,
        color: '#F2E3FF',
        marginLeft: 6,
        fontSize: 11,
    },
    refMitButton: {
        alignItems: 'center',
        marginBottom: 16,
    },
    refMitButtonInner: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#F8C2FF',
    },
    refMitText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginLeft: 8,
    },
    refSection: {
        marginBottom: 12,
    },
    refSectionLabel: {
        ...FONTS.Title3,
        color: '#A77CC8',
        textAlign: 'center',
        marginBottom: 4,
    },
    refSectionValue: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        textAlign: 'center',
    },
    refArchetypeImage: {
        width: '84%',
        aspectRatio: 1,
        alignSelf: 'center',
        borderRadius: 10,
        marginTop: 10,
    },
    refArchetypeTagRow: {
        marginTop: 10,
        flexDirection: 'row',
        justifyContent: 'center',
        flexWrap: 'wrap',
        gap: 6,
    },
    refArchetypeTag: {
        ...FONTS.Title2,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 5,
        overflow: 'hidden',
    },
    refArchetypeDescription: {
        ...FONTS.Title2,
        color: COLORS.LIGHTGREY,
        textAlign: 'center',
        marginTop: 10,
        lineHeight: 20,
        paddingHorizontal: 8,
    },
    refCruNameText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        textAlign: 'center',
        marginTop: 10,
    },
    refCruNameLabel: {
        ...FONTS.Title2,
        color: COLORS.AKCRUPINK,
    },
    refGalleryWrap: {
        marginBottom: 16,
    },
    refGalleryGridThreeCol: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: 4,

    },
    refGalleryGridThreeColItem: {
        width: '32%',
    },
    refGalleryGridThreeColImage: {
        width: '100%',
        aspectRatio: 1,
    },
    refFooterActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    refPinnedFooterContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#000000',
        borderTopWidth: 1,
        borderTopColor: '#2A2A2A',
        paddingHorizontal: 14,
        paddingTop: 10,
        paddingBottom: 12,
    },
    refFooterBtn: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#8050AF',
        borderRadius: UNIFIED_BUTTON_RADIUS,
        paddingVertical: 10,
        backgroundColor: 'rgba(19, 4, 39, 0.65)',
    },
    refFooterBtnText: {
        ...FONTS.Title3,
        color: '#F3DFFF',
        marginLeft: 6,
    },
    cruinvitebutton: {
        width: 125,
        height: 30,
        backgroundColor: COLORS.AKCRUBLUE,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: UNIFIED_BUTTON_RADIUS,
        marginRight: 10,
    },
    followbutton: {
        width: '25%',
        height: 30,
        backgroundColor: COLORS.CATPURPLGT,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: UNIFIED_BUTTON_RADIUS,
    },
    unfollowbutton: {
        width: 125,
        height: 30,
        backgroundColor: COLORS.CATPURPDRK,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: UNIFIED_BUTTON_RADIUS,
    },
    watchlisttext: {
        ...FONTS.Title2,
        marginTop: 10,
        marginBottom: -20,
    },
    watchlistcontainer: {
        marginHorizontal: 15,
        marginBottom: 10,
    },
    seperator: {
        borderBottomWidth: 1.5,
        borderColor: COLORS.DARKERGREY,
        marginTop: 20,
        marginBottom: 10,
        marginHorizontal: 15,
    },
    desctext: {
        ...FONTS.Title2,
        marginTop: '5%',
        marginBottom: 20,
        textAlign: 'center',
        textDecorationLine: 'underline',
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    gallerycontainer: {
        marginHorizontal: '1%',
    },

    galleryImagesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center', // Align items at the start of each row
        marginTop: 20,
    },
    galleryImage: {
        width: (SIZES.ScreenWidth - SIZES.marginhorizontal * 2 - 30) / 3, // Adjust width to fit 3 images per row with margins
        height: ((SIZES.ScreenWidth - SIZES.marginhorizontal * 2 - 30) / 3) * 1.5, // Adjust height proportionally
        margin: 5,
        borderRadius: 5,
    },

    selectedPhotoContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    selectedPhoto: {
        width: SIZES.ScreenWidth,
        aspectRatio: 1,
        opacity: 0,
        marginTop: -100,
    },
});
