

export type ArchetypeMapping = {
    [key: string]: {
    name:string;
    image:string;
};
};

export const archetypeMapping: ArchetypeMapping = {
    'Sci-Fi, Fantasy': {name: 'Realm Voyager', image: ''},
    'Sci-Fi, Drama': {name: 'Whimsical Dreamer', image: ''},
    'Sci-Fi, Mystery': {name: 'Mystical Puzzler', image: ''},
    'Sci-Fi, Thriller': {name: 'Shadow Sleuth', image: ''},
    'Sci-Fi, Comedy': {name: 'Fantasy Fun-seeker', image: ''},
    'Sci-Fi, Sports': {name: 'Realm Athlete', image: ''},
    'Sci-Fi, Family': {name: 'Tribe Seeker', image: ''},
    'Sci-Fi, Horror': {name: 'Dark Explorer', image: ''},
    'Sci-Fi, Action': {name: 'Sorcery Warrior', image: ''},
    'Sci-Fi, Crime': {name: 'Fantasy Detective ', image: ''},
    'Sci-Fi, Adventure': {name: 'Adventurous Nior', image: ''},
    'Sci-Fi, Romance': {name: 'Cosmic Romancer', image: ''},
    'Fantasy, Sci-Fi': {name: 'Realm Voyager', image: ''},
    'Fantasy, Drama': {name: 'Whimsical Dreamer', image: ''},
    'Fantasy, Mystery': {name: 'Mystical Puzzler', image: ''},
    'Fantasy, Thriller': {name: 'Shadow Sleuth', image: ''},
    'Fantasy, Comedy': {name: 'Fantasy Fun-seeker', image: ''},
    'Fantasy, Sports': {name: 'Realm Athlete', image: ''},
    'Fantasy, Family': {name: 'Tribe Seeker', image: ''},
    'Fantasy, Horror': {name: 'Dark Explorer', image: ''},
    'Fantasy, Action': {name: 'Sorcery Warrior', image: ''},
    'Fantasy, Crime': {name: 'Fantasy Detective ', image: ''},
    'Fantasy, Adventure': {name: 'Adventurous Nior', image: ''},
    'Fantasy, Romance': {name: 'Enchanted Dreamer', image: ''},
    'Drama, Fantasy': {name: 'Whimsical Dreamer', image: ''},
    'Drama, Sci-Fi': {name: 'Emotional Explorer', image: ''},
    'Drama, Mystery': {name: 'Dramatic Observer', image: ''},
    'Drama, Thriller': {name: 'Chilling Chaser', image: ''},
    'Drama, Comedy': {name: 'Witty Joker', image: ''},
    'Drama, Sports': {name: 'Competitive Dreamer', image: ''},
    'Drama, Family': {name: 'Emotional Connector', image: ''},
    'Drama, Horror': {name: 'Darkly Suspenseful', image: ''},
    'Drama, Action': {name: 'Curious Defender', image: ''},
    'Drama, Crime': {name: 'Smooth Criminal ', image: ''},
    'Drama, Adventure': {name: 'Emotional Rollercoaster', image: ''},
    'Drama, Romance': {name: 'Fantasy Paramour', image: ''},
    'Mystery, Fantasy': {name: 'Mystical Puzzler', image: ''},
    'Mystery, Sci-Fi': {name: 'Quantum Detective', image: ''},
    'Mystery, Drama': {name: 'Dramatic Observer', image: ''},
    'Mystery, Thriller': {name: 'Bone Collector', image: ''},
    'Mystery, Comedy': {name: 'Mocking Bird ', image: ''},
    'Mystery, Sports': {name: 'Athletic Sleuth', image: ''},
    'Mystery, Family': {name: 'Stealth Clan', image: ''},
    'Mystery, Horror': {name: 'Black Magic Seeker', image: ''},
    'Mystery, Action': {name: 'Thrill Seeker', image: ''},
    'Mystery, Crime': {name: 'Shadow Agent', image: ''},
    'Mystery, Adventure': {name: 'Treasure Hunter', image: ''},
    'Mystery, Romance': {name: 'Evasive Enigma', image: ''},
    'Thriller, Fantasy': {name: 'Shadow Sleuth', image: ''},
    'Thriller, Sci-Fi': {name: 'Cyber Thrillseeker', image: ''},
    'Thriller, Drama': {name: 'Chilling Chaser', image: ''},
    'Thriller, Mystery': {name: 'Bone Collector', image: ''},
    'Thriller, Comedy': {name: 'Adrenaline Chuckler', image: ''},
    'Thriller, Sports': {name: 'Mystery Challenger', image: ''},
    'Thriller, Family': {name: 'Curious Guardian', image: ''},
    'Thriller, Horror': {name: 'Terror Seeker', image: ''},
    'Thriller, Action': {name: 'Action Maverick', image: ''},
    'Thriller, Crime': {name: 'Criminal Minded', image: ''},
    'Thriller, Adventure': {name: 'Action Junkie', image: ''},
    'Thriller, Romance': {name: 'Suspenseful Heartbeat', image: ''},
    'Comedy, Fantasy': {name: 'Fantasy Fun-seeker', image: ''},
    'Comedy, Sci-Fi': {name: 'Cosmic Jester', image: ''},
    'Comedy, Drama': {name: 'Witty Joker', image: ''},
    'Comedy, Mystery': {name: 'Mocking Bird', image: ''},
    'Comedy, Thriller': {name: 'Adrenaline Chuckler', image: ''},
    'Comedy, Sports': {name: 'Playful Sportster', image: ''},
    'Comedy, Family': {name: 'Comedic Connector', image: ''},
    'Comedy, Horror': {name: 'Dark Giggler', image: ''},
    'Comedy, Action': {name: 'Laughing Hero', image: ''},
    'Comedy, Crime': {name: 'Smiling Convict', image: ''},
    'Comedy, Adventure': {name: 'Laughing Trailblazer', image: ''},
    'Comedy, Romance': {name: 'Charming Jester', image: ''},
    'Sports, Fantasy': {name: 'Realm Athlete', image: ''},
    'Sports, Sci-Fi': {name: 'Space Jock', image: ''},
    'Sports, Drama': {name: 'Competitive Dreamer', image: ''},
    'Sports, Mystery': {name: 'Athletic Sleuth', image: ''},
    'Sports, Thriller': {name: 'Mystery Challenger', image: ''},
    'Sports, Comedy': {name: 'Playful Sportster', image: ''},
    'Sports, Family': {name: 'Group Huddler', image: ''},
    'Sports, Horror': {name: 'Bloody Player', image: ''},
    'Sports, Action': {name: 'Gridiron Gladiator', image: ''},
    'Sports, Crime': {name: 'Criminal Competitor', image: ''},
    'Sports, Adventure': {name: 'Odyssey Champion', image: ''},
    'Sports, Romance': {name: 'Love Gamechanger', image: ''},
    'Family, Fantasy': {name: 'Tribe Seeker', image: ''},
    'Family, Sci-Fi': {name: 'Interstellar Bonder', image: ''},
    'Family, Drama': {name: 'Emotional Connector', image: ''},
    'Family, Mystery': {name: 'Stealth Clan', image: ''},
    'Family, Thriller': {name: 'Curious Guardian', image: ''},
    'Family, Comedy': {name: 'Comedic Connector', image: ''},
    'Family, Sports': {name: 'Group Huddler', image: ''},
    'Family, Horror': {name: 'Chilling Lover', image: ''},
    'Family, Action': {name: 'Family  Defender', image: ''},
    'Family, Crime': {name: 'Crime Bonder', image: ''},
    'Family, Adventure': {name: 'Family  Explorer', image: ''},
    'Family, Romance': {name: 'Kinship Lover', image: ''},
    'Horror, Fantasy': {name: 'Dark Explorer', image: ''},
    'Horror, Sci-Fi': {name: 'Eerie Futurist', image: ''},
    'Horror, Drama': {name: 'Darkly Suspenseful', image: ''},
    'Horror, Mystery': {name: 'Black Magic Seeker', image: ''},
    'Horror, Thriller': {name: 'Terror Seeker', image: ''},
    'Horror, Comedy': {name: 'Dark Giggler', image: ''},
    'Horror, Sports': {name: 'Bloody Player', image: ''},
    'Horror, Family': {name: 'Chilling Lover', image: ''},
    'Horror, Action': {name: 'Blood and Bullets', image: ''},
    'Horror, Crime': {name: 'Terror Killer', image: ''},
    'Horror, Adventure': {name: 'Dark Passenger', image: ''},
    'Horror, Romance': {name: 'Romantic Dread', image: ''},
    'Action, Fantasy': {name: 'Sorcery Warrior', image: ''},
    'Action, Sci-Fi': {name: 'Galactic Hero', image: ''},
    'Action, Drama': {name: 'Curious Defender', image: ''},
    'Action, Mystery': {name: 'Thrill Seeker', image: ''},
    'Action, Thriller': {name: 'Action Maverick', image: ''},
    'Action, Comedy': {name: 'Laughing Hero', image: ''},
    'Action, Sports': {name: 'Gridiron Gladiator', image: ''},
    'Action, Family': {name: 'Family Defender', image: ''},
    'Action, Horror': {name: 'Blood and Bullets', image: ''},
    'Action, Crime': {name: 'Crime Dynamo', image: ''},
    'Action, Adventure': {name: 'Thrill Voyager', image: ''},
    'Action, Romance': {name: 'Adventurous Lover', image: ''},
    'Crime, Fantasy': {name: 'Fantasy Detective', image: ''},
    'Crime, Sci-Fi': {name: 'Space Crime Puzzler', image: ''},
    'Crime, Drama': {name: 'Smooth Criminal', image: ''},
    'Crime, Mystery': {name: 'Shadow Agent', image: ''},
    'Crime, Thriller': {name: 'Criminal Minded', image: ''},
    'Crime, Comedy': {name: 'Smiling Convict', image: ''},
    'Crime, Sports': {name: 'Criminal Competitor', image: ''},
    'Crime, Family': {name: 'Crime Bonder', image: ''},
    'Crime, Horror': {name: 'Terror Killer', image: ''},
    'Crime, Action': {name: 'Crime Dynamo', image: ''},
    'Crime, Adventure': {name: 'Outlaw Crusader', image: ''},
    'Crime, Romance': {name: 'Larcenous Heart', image: ''},
    'Adventure, Fantasy': {name: 'Adventurous Nior', image: ''},
    'Adventure, Sci-Fi': {name: 'Interstellar Trekker', image: ''},
    'Adventure, Drama': {name: 'Emotional Rollercoaster ', image: ''},
    'Adventure, Mystery': {name: 'Treasure Hunter', image: ''},
    'Adventure, Thriller': {name: 'Action Junkie', image: ''},
    'Adventure, Comedy': {name: 'Laughing Trailblazer', image: ''},
    'Adventure, Sports': {name: 'Odyssey Champion', image: ''},
    'Adventure, Family': {name: 'Family Explorer', image: ''},
    'Adventure, Horror': {name: 'Dark Passenger', image: ''},
    'Adventure, Action': {name: 'Thrill Voyager', image: ''},
    'Adventure, Crime': {name: 'Outlaw Crusader', image: ''},
    'Adventure, Romance': {name: 'Risky Romantic', image: ''},
    'Romance, Fantasy': {name: 'Enchanted Dreamer', image: ''},
    'Romance, Sci-Fi': {name: 'Cosmic Romancer', image: ''},
    'Romance, Drama': {name: 'Fantasy Paramour', image: ''},
    'Romance, Mystery': {name: 'Evasive Enigma', image: ''},
    'Romance, Thriller': {name: 'Suspenseful Heartbeat', image: ''},
    'Romance, Comedy': {name: 'Charming Jester', image: ''},
    'Romance, Sports': {name: 'Love Gamechanger', image: ''},
    'Romance, Family': {name: 'Kinship Lover', image: ''},
    'Romance, Horror': {name: 'Romantic Dread', image: ''},
    'Romance, Action': {name: 'Adventurous Lover', image: ''},
    'Romance, Crime': {name: 'Larcenous Heart', image: ''},
    'Romance, Adventure': {name: 'Risky Romantic', image: ''},
    
    // Define more mappings here...
};

const archetypeData = {archetypeMapping};

export default archetypeData;