

export type ArchetypeMapping = {
    [key: string]: string;
};

export const archetypeMapping: ArchetypeMapping = {
    'Sci-Fi, Fantasy': 'Realm Voyager',
    'Sci-Fi, Drama': 'Whimsical Dreamer',
    'Sci-Fi, Mystery': 'Mystical Puzzler',
    'Sci-Fi, Thriller': 'Shadow Sleuth',
    'Sci-Fi, Comedy': 'Fantasy Fun-seeker',
    'Sci-Fi, Sports': 'Realm Athlete',
    'Sci-Fi, Family': 'Tribe Seeker',
    'Sci-Fi, Horror': 'Dark Explorer',
    'Sci-Fi, Action': 'Sorcery Warrior',
    'Sci-Fi, Crime': 'Fantasy Detective ',
    'Sci-Fi, Adventure': 'Adventurous Nior',
    'Sci-Fi, Romance': 'Cosmic Romancer',
    'Fantasy, Sci-Fi': 'Realm Voyager',
    'Fantasy, Drama': 'Whimsical Dreamer',
    'Fantasy, Mystery': 'Mystical Puzzler',
    'Fantasy, Thriller': 'Shadow Sleuth',
    'Fantasy, Comedy': 'Fantasy Fun-seeker',
    'Fantasy, Sports': 'Realm Athlete',
    'Fantasy, Family': 'Tribe Seeker',
    'Fantasy, Horror': 'Dark Explorer',
    'Fantasy, Action': 'Sorcery Warrior',
    'Fantasy, Crime': 'Fantasy Detective ',
    'Fantasy, Adventure': 'Adventurous Nior',
    'Fantasy, Romance': 'Enchanted Dreamer',
    'Drama, Fantasy': 'Whimsical Dreamer',
    'Drama, Sci-Fi': 'Emotional Explorer',
    'Drama, Mystery': 'Dramatic  Observer',
    'Drama, Thriller': 'Chilling Chaser',
    'Drama, Comedy': 'Witty Joker',
    'Drama, Sports': 'Competitive Dreamer',
    'Drama, Family': 'Emotional Connector',
    'Drama, Horror': 'Darkly Suspenseful',
    'Drama, Action': 'Curious Defender',
    'Drama, Crime': 'Smooth Criminal ',
    'Drama, Adventure': 'Emotional Rollercoaster ',
    'Drama, Romance': 'Fantasy Paramour',
    'Mystery, Fantasy': 'Mystical Puzzler',
    'Mystery, Sci-Fi': 'Quantum Detective',
    'Mystery, Drama': 'Dramatic  Observer',
    'Mystery, Thriller': 'Bone Collector',
    'Mystery, Comedy': 'Mocking Bird ',
    'Mystery, Sports': 'Athletic Sleuth',
    'Mystery, Family': 'Stealth Clan',
    'Mystery, Horror': 'Black Magic Seeker',
    'Mystery, Action': 'Thrill Seeker',
    'Mystery, Crime': 'Shadow Agent',
    'Mystery, Adventure': 'Treasure Hunter',
    'Mystery, Romance': 'Evasive Enigma',
    'Thriller, Fantasy': 'Shadow Sleuth',
    'Thriller, Sci-Fi': 'Cyber Thrillseeker',
    'Thriller, Drama': 'Chilling Chaser',
    'Thriller, Mystery': 'Bone Collector',
    'Thriller, Comedy': 'Adrenaline Chuckler',
    'Thriller, Sports': 'Mystery Challenger',
    'Thriller, Family': 'Curious Guardian',
    'Thriller, Horror': 'Terror Seeker',
    'Thriller, Action': 'Action Maverick',
    'Thriller, Crime': 'Criminal Minded',
    'Thriller, Adventure': 'Action Junkie',
    'Thriller, Romance': 'Suspenseful Heartbeat',
    'Comedy, Fantasy': 'Fantasy Fun-seeker',
    'Comedy, Sci-Fi': 'Cosmic Jester',
    'Comedy, Drama': 'Witty Joker',
    'Comedy, Mystery': 'Mocking Bird',
    'Comedy, Thriller': 'Adrenaline Chuckler',
    'Comedy, Sports': 'Playful Sportster',
    'Comedy, Family': 'Comedic Connector',
    'Comedy, Horror': 'Dark Giggler',
    'Comedy, Action': 'Laughing Hero',
    'Comedy, Crime': 'Smiling Convict',
    'Comedy, Adventure': 'Laughing Trailblazer',
    'Comedy, Romance': 'Charming Jester',
    'Sports, Fantasy': 'Realm Athlete',
    'Sports, Sci-Fi': 'Space Jock',
    'Sports, Drama': 'Competitive Dreamer',
    'Sports, Mystery': 'Athletic Sleuth',
    'Sports, Thriller': 'Mystery Challenger',
    'Sports, Comedy': 'Playful Sportster',
    'Sports, Family': 'Group Huddler',
    'Sports, Horror': 'Bloody Player',
    'Sports, Action': 'Gridiron Gladiator',
    'Sports, Crime': 'Criminal Competitor',
    'Sports, Adventure': 'Odyssey Champion',
    'Sports, Romance': 'Love Gamechanger',
    'Family, Fantasy': 'Tribe Seeker',
    'Family, Sci-Fi': 'Interstellar Bonder',
    'Family, Drama': 'Emotional Connector',
    'Family, Mystery': 'Stealth Clan',
    'Family, Thriller': 'Curious Guardian',
    'Family, Comedy': 'Comedic Connector',
    'Family, Sports': 'Group Huddler',
    'Family, Horror': 'Chilling Lover',
    'Family, Action': ' Family  Defender',
    'Family, Crime': 'Crime Bonder',
    'Family, Adventure': 'Family  Explorer',
    'Family, Romance': 'Kinship Lover',
    'Horror, Fantasy': 'Dark Explorer',
    'Horror, Sci-Fi': 'Eerie Futurist',
    'Horror, Drama': 'Darkly Suspenseful',
    'Horror, Mystery': 'Black Magic Seeker',
    'Horror, Thriller': 'Terror Seeker',
    'Horror, Comedy': 'Dark Giggler',
    'Horror, Sports': 'Bloody Player',
    'Horror, Family': 'Chilling Lover',
    'Horror, Action': 'Blood and Bullets',
    'Horror, Crime': 'Terror Killer',
    'Horror, Adventure': 'Dark Passenger',
    'Horror, Romance': 'Romantic Dread',
    'Action, Fantasy': 'Sorcery Warrior',
    'Action, Sci-Fi': 'Galactic Hero',
    'Action, Drama': 'Curious Defender',
    'Action, Mystery': 'Thrill Seeker',
    'Action, Thriller': 'Action Maverick',
    'Action, Comedy': 'Laughing Hero',
    'Action, Sports': 'Gridiron Gladiator',
    'Action, Family': 'Family Defender',
    'Action, Horror': 'Blood and Bullets',
    'Action, Crime': 'Crime Dynamo',
    'Action, Adventure': 'Thrill Voyager',
    'Action, Romance': 'Adventurous Lover',
    'Crime, Fantasy': 'Fantasy Detective',
    'Crime, Sci-Fi': 'Space Crime Puzzler',
    'Crime, Drama': 'Smooth Criminal',
    'Crime, Mystery': 'Shadow Agent',
    'Crime, Thriller': 'Criminal Minded',
    'Crime, Comedy': 'Smiling Convict',
    'Crime, Sports': 'Criminal Competitor',
    'Crime, Family': 'Crime Bonder',
    'Crime, Horror': 'Terror Killer',
    'Crime, Action': 'Crime Dynamo',
    'Crime, Adventure': 'Outlaw Crusader',
    'Crime, Romance': 'Larcenous Heart',
    'Adventure, Fantasy': 'Adventurous Nior',
    'Adventure, Sci-Fi': 'Interstellar Trekker',
    'Adventure, Drama': 'Emotional Rollercoaster ',
    'Adventure, Mystery': 'Treasure Hunter',
    'Adventure, Thriller': 'Action Junkie',
    'Adventure, Comedy': 'Laughing Trailblazer',
    'Adventure, Sports': 'Odyssey Champion',
    'Adventure, Family': 'Family Explorer',
    'Adventure, Horror': 'Dark Passenger',
    'Adventure, Action': 'Thrill Voyager',
    'Adventure, Crime': 'Outlaw Crusader',
    'Adventure, Romance': 'Risky Romantic',
    'Romance, Fantasy': 'Enchanted Dreamer',
    'Romance, Sci-Fi': 'Cosmic Romancer',
    'Romance, Drama': 'Fantasy Paramour',
    'Romance, Mystery': 'Evasive Enigma',
    'Romance, Thriller': 'Suspenseful Heartbeat',
    'Romance, Comedy': 'Charming Jester',
    'Romance, Sports': 'Love Gamechanger',
    'Romance, Family': 'Kinship Lover',
    'Romance, Horror': 'Romantic Dread',
    'Romance, Action': 'Adventurous Lover',
    'Romance, Crime': 'Larcenous Heart',
    'Romance, Adventure': 'Risky Romantic',
    
    // Define more mappings here...
};

const archetypeData = {archetypeMapping};

export default archetypeData;