import { AKCRUBADGES } from "./theme";

const skinnies = [
    {
        id: 't0',
        user: {
            id: 'u1',
            username: 'VadimNotJustDev',
            name: 'Vadim',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/vadim.png',
            akcruBadge: {superhero: true},
            avatarbordercolor: AKCRUBADGES.SuperHero.color,
            influencer: false,
        },
        createdAt: '2020-08-27T12:00:00.000Z',
        content: "Everyone should watch E3! Great freakin' movie",
        image: 'https://www.themoviedb.org/t/p/w220_and_h330_face/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg',
        numberOfComments: 123,
        numberOfReposts: 11,
        numberOfLikes: 10,
        impressions: 1300,
    },
    {
        id: '111111111',
        createdAt: '2023-04-28T08:30:00.000Z',
        user: {
            id: '123456789',
            name: 'Jeff B',
            username: 'bezos',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/jeff.jpeg',
            akcruBadge: {guardian: true},
            avatarbordercolor: AKCRUBADGES.Guardian.color,
            influencer: true,
        },
        content: 'Just had a great workout at the gym! 💪 #fitness #healthylifestyle',
        numberOfComments: 2,
        numberOfReposts: 5,
        numberOfLikes: 25,
        impressions: 500,
    },
    {
        id: '222222222',
        createdAt: '2023-04-27T19:45:00.000Z',
        user: {
            id: '987654321',
            name: 'Zuck',
            username: 'zuck',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/zuck.jpeg',
            akcruBadge: {hero: true},
            avatarbordercolor: AKCRUBADGES.Hero.color,
            influencer: false,
        },
        content: 'Bullet Train is a must see. Loved it',
        image: 'https://cdn.forumcomm.com/dims4/default/89949be/2147483647/strip/true/crop/1199x799+0+1/resize/840x560!/quality/90/?url=https%3A%2F%2Fforum-communications-production-web.s3.us-west-2.amazonaws.com%2Fbrightspot%2F63%2F3a%2F1969c76f4edc99edb76fa61b1e84%2Fbullet-train-movie-poster.jpg',
        numberOfComments: 10,
        numberOfReposts: 20,
        numberOfLikes: 100,
        impressions: 1000,
    },
    {
        id: '333333333',
        createdAt: '2023-04-26T12:00:00.000Z',
        user: {
            id: '123456789',
            name: 'Jane Smith',
            username: 'janesmith',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/6.png',
            akcruBadge: {akcruit: true},
            avatarbordercolor: AKCRUBADGES.Akcruit.color,
            influencer: false,
        },
        content:
            'Excited to announce that I will be speaking at the upcoming Akcru Film festival in New York! 🎉 #womenintech',
        numberOfComments: 5,
        numberOfReposts: 10,
        numberOfLikes: 50,
        impressions: 1000,
    },
    {
        id: 't1',
        user: {
            id: 'u1',
            username: 'VadimNotJustDev',
            name: 'Vadim',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/vadim.png',
            akcruBadge: {superhero: true},
            avatarbordercolor: AKCRUBADGES.SuperHero.color,
            influencer: false,
        },
        createdAt: '2020-08-27T12:00:00.000Z',
        content:
            'So who wants to watch a movie with me? My Cru keeps wanting to watch the same movie over and over again ugh #Ineedanewcru.',
        image: 'https://i.insider.com/5d03aa8e6fc9201bc7002b43?width=1136&format=jpeg',
        numberOfComments: 123,
        numberOfReposts: 11,
        numberOfLikes: 10,
        impressions: 200,
    },
    {
        id: 't2',
        user: {
            id: 'u1',
            username: 'VadimNotJustDev',
            name: 'Vadim',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/vadim.png',
            akcruBadge: {superhero: true},
            avatarbordercolor: AKCRUBADGES.SuperHero.color,
            influencer: false,
        },
        createdAt: '2020-08-27T12:00:00.000Z',
        content: "Hey Hey Hey, I just watched a movie with my future wife. I'm in love lol.",
        numberOfComments: 4,
        numberOfReposts: 11,
        numberOfLikes: 99,
        impressions: 330,
    },
    {
        id: 't3',
        user: {
            id: 'u1',
            username: 'VadimNotJustDev',
            name: 'Vadim',
            image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/vadim.png',
            akcruBadge: {superhero: true},
            avatarbordercolor: AKCRUBADGES.SuperHero.color,
            influencer: false,
        },
        createdAt: '2020-08-27T12:00:00.000Z',
        content: 'I wanna marry Trinity.',
        numberOfComments: 4,
        numberOfReposts: 11,
        numberOfLikes: 99,
        impressions: 100,
    },
    {
        id: 't4',
        user: {
            id: 'u12',
            username: 'Big Homie',
            name: 'GodFatherPt3',
            image: 'https://variety.com/wp-content/uploads/2022/01/godfather-of-harlem.jpg',
            akcruBadge: {guardian: true},
            avatarbordercolor: AKCRUBADGES.SuperHero.color,
            influencer: false,
        },
        createdAt: '2020-08-27T12:00:00.000Z',
        content: 'Check out my movie review on Den of Thieves. Only Gaurdians can do this. lol',
        numberOfComments: 67,
        numberOfReposts: 444,
        numberOfLikes: 99,
        impressions: 1400,
        video: 'https://d17ybuhl825fg.cloudfront.net/sample+videos/Kwaz+review.mp4',
    },
];

export default skinnies;
