import {StyleSheet, Platform} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants/index';

export default StyleSheet.create({
    scheduleBg: {
        flex: 1,
    },
    scheduleOverlay: {
        flex: 1,
    },
    scheduleContent: {
        paddingHorizontal: 16,
        paddingBottom: 40,
    },
    scheduleTitle: {
        ...FONTS.Title1,
        color: '#F3D9FF',
        textAlign: 'center',
        marginTop: 14,marginBottom: 14,
    },
    scheduleSubtitle: {
        ...FONTS.paragraph2,
        color: '#D4C8F8',
        textAlign: 'center',
        marginTop: 4,
        marginBottom: 14,
    },
    schedulePairOuter: {
        borderRadius: 18,
        padding: 1.2,
        overflow: 'hidden',
        shadowColor: '#C15DFF',
        shadowOpacity: 0.55,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: 0},
        elevation: 8,
    },
    schedulePairBeam: {
        position: 'absolute',
        left: 14,
        right: 14,
        top: 46,
        height: 3,
        borderRadius: 3,
    },
    scheduleTravelGlow: {
        position: 'absolute',
        top: 0,
        width: 100,
        height: 100,
        zIndex: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scheduleTravelIcon: {
        width: 100,
        height: 100,
        resizeMode: 'contain',
    },
    schedulePairInner: {
        borderRadius: 17,
        backgroundColor: 'rgba(10, 6, 33, 0.9)',
        paddingVertical: 12,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    schedulePairUser: {
        width: '36%',
        alignItems: 'center',
    },
    scheduleTicketSlot: {
        height: 66,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scheduleTicketIcon: {
        width: 48,
        height: 26,
        resizeMode: 'contain',
    },
    scheduleUserName: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginTop: 8,
        textAlign: 'center',
    },
    scheduleMetaText: {
        ...FONTS.paragraph2,
        color: '#C4B5FD',
        marginTop: 4,
        textAlign: 'center',
    },
    scheduleFieldLabel: {
        ...FONTS.Title2,
        color: '#E8C5FF',
        marginTop: 14,
        marginBottom: 8,
    },
    schedulePickerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    scheduleArrowButton: {
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(127, 97, 255, 0.3)',
    },
    scheduleMonthText: {
        ...FONTS.Title2,
        color: '#E9E1FF',
    },
    kickoffOuter: {
        borderRadius: 14,
        padding: 1.2,
        marginTop: 4,
    },
    kickoffInner: {
        borderRadius: 13,
        backgroundColor: 'rgba(15, 10, 38, 0.95)',
        minHeight: 92,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    kickoffInput: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        minHeight: 72,
        textAlignVertical: 'top',
    },
    scheduleSendWrap: {
        marginTop: 20,
        alignItems: 'center',
    },
    input: {
        flexDirection: 'row',
        borderWidth: 0.8,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        justifyContent: 'space-between',
        marginVertical: 10,
        paddingLeft: 10,
        alignItems: 'flex-start',
        height: 150,
    },
    textinput: {
        color: COLORS.LIGHTGREY,
    },
    sendbutton: {
        backgroundColor: COLORS.AKCRUBLUE,
        height: 35,
        justifyContent: 'center',
        width: 90,
        borderRadius: 5,
        alignItems: 'center',
    },
    topcontainer: {
        marginHorizontal: 15,

    },
    screenTitle: {
        ...FONTS.Title3,
        marginTop: 10,
        marginBottom: 10,
        marginRight: 10,
    },
    choosedate: {
        ...FONTS.Title3,
        marginTop: 10,
        marginBottom: 10,
        marginRight: 10,
        textAlign: 'center',
        textDecorationLine: 'underline',
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    //Starting Picker Styles
    container: {
        marginHorizontal: 15,
    },
    monthContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    monthText: {
        ...FONTS.Title3,
        marginHorizontal: 10,
        color: COLORS.AKCRUBLUE,
    },
    arrowButton: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    arrowbuttonstyle: {
        color: COLORS.WHITE,
        fontSize: 18,
    },
    datePickerContainer: {
        flexDirection: 'row',
        marginTop: 10,
        marginBottom: 10,
    },
    dayButton: {
        width: 60,
        height: 60,
        borderRadius: 12,
        backgroundColor: 'rgba(21, 14, 52, 0.92)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(170, 139, 255, 0.45)',
    },
    dayButtonSelected: {
        backgroundColor: '#7D4DFF',
        borderColor: '#CA9DFF',
    },
    dayText: {
        ...FONTS.Title2,
    },
    dayTextSelected: {
        color: 'white',
    },
    dayOfWeekText: {
        ...FONTS.Title2,
        marginTop: 5,
    },
    timePickerContainer: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    timeButton: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: 'rgba(21, 14, 52, 0.92)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(170, 139, 255, 0.45)',
    },
    timeButtonSelected: {
        backgroundColor: '#7D4DFF',
        borderColor: '#CA9DFF',
    },
    timeText: {
        ...FONTS.Title2,
    },
    timeTextSelected: {
        color: 'white',
    },
    timeZonePickerContainer: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    timeZoneButton: {
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: 'rgba(21, 14, 52, 0.92)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(170, 139, 255, 0.45)',
    },
    timeZoneButtonSelected: {
        backgroundColor: '#7D4DFF',
        borderColor: '#CA9DFF',
    },
    timeZoneText: {
        ...FONTS.Title2,
    },
    timeZoneTextSelected: {
        color: 'white',
    },
    selectedDateTimeContainer: {
        marginTop: 20,
        marginBottom: 10,
    },
    selectedDateTimeText: {
        ...FONTS.Title2,
        marginBottom: 5,
    },
    disabledButton: {
        opacity: 0.5,
    },
    //User picker styles
    usermitsearchinput: {
        width: SIZES.ScreenWidth / 1.1,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginVertical: 10,
        alignItems: 'center',
        height: 40,
    },
    activitycontainer: {
        height: SIZES.ScreenHeight,
        width: SIZES.ScreenWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchinput: {
        width: SIZES.ScreenWidth / 1.08,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginVertical: 10,
        alignItems: 'center',
        height: 40,
        justifyContent: 'space-between',
    },
    backbutton: {
        backgroundColor: COLORS.BLACK,
        marginTop: Platform.OS === 'ios' ? '10%' : 0,
    },
    ticketContainer: {
        width: SIZES.ScreenWidth / 1.22,
        height: SIZES.ScreenWidth / 0.88,
        borderTopLeftRadius: 14,
        borderTopRightRadius: 14,
        borderStyle: 'dashed',
        borderColor: '#000000',
        borderBottomWidth: 2,
    },
    ticketImage: {
        overflow: 'hidden',
        alignSelf: 'center',
        width: SIZES.ScreenWidth / 1.22,
        height: SIZES.ScreenWidth / 0.88,
        borderTopLeftRadius: 14,
        borderTopRightRadius: 14,
        justifyContent: 'flex-end',
    },
    ticketFooter: {
        padding: 12,
        backgroundColor: COLORS.AKCRUBLUE,
        width: SIZES.ScreenWidth / 1.22,
        height: SIZES.ScreenWidth / 2.2,
        borderBottomLeftRadius: 14,
        borderBottomRightRadius: 14,
        borderStyle: 'dashed',
        borderColor: COLORS.AKCRUBACKGROUND,
        borderTopWidth: 2,
        overflow: 'hidden',
    },
    linearGradient: {
        height: '70%',
    },
    ticketCircle: {
        height: 80,
        width: 80,
        borderRadius: 80,
        backgroundColor: COLORS.BLACK,
    },
    defaultDiscoveryWrap: {
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(116,133,255,0.38)',
        backgroundColor: COLORS.BLACK,
    },
    discoverySectionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 14,
        marginBottom: 2,
    },
    discoverySectionTitleIcon: {
        marginRight: 10,
    },
    defaultSectionTitle: {
        ...FONTS.Title3,
        color: '#F4B6FF',
        marginBottom: 6,
    },
    defaultSuggestionText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginBottom: 4,
    },
    defaultProfileGradient: {
        borderRadius: 14,
        padding: 1.2,
        marginTop: 12,
        shadowColor: '#9D63FF',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.35,
        shadowRadius: 8,
        elevation: 3,
    },
    defaultProfileGradientPressed: {
        padding: 0,
        borderRadius: 15,
        shadowOpacity: 0.65,
        shadowRadius: 18,
        shadowOffset: {width: 0, height: 4},
        elevation: 10,
    },
    /** Keep selected card width equal to unselected card width. */
    profileCardSelectedScale: {
        transform: [{scale: 1}],
    },
    /** Selected card: outer gradient ring (padding = border thickness). */
    profileCardGradientBorderOuter: {
        borderRadius: 15,
        padding: 1,
        overflow: 'hidden',
    },
    profileCardGradientBorderInner: {
        borderRadius: 13,
        backgroundColor: COLORS.BLACK,
        overflow: 'hidden',
    },
    defaultProfileInner: {
        borderRadius: 13,
        backgroundColor: COLORS.BLACK,
        paddingVertical: 11,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    defaultProfileInfo: {
        flex: 1,
        marginHorizontal: 10,
    },
    defaultProfileName: {
        ...FONTS.Title3,
        color: COLORS.WHITE,
    },
    defaultProfileMatch: {
        ...FONTS.Title2,
        color: '#8AD6FF',
        marginTop: 2,
    },
    defaultProfileDesc: {
        ...FONTS.paragraph2,
        color: '#D8D7FF',
        marginTop: 2,
    },
    defaultInviteBar: {
        borderRadius: 18,
        padding: 1.3,
        marginBottom: 14,
    },
    defaultInviteInner: {
        borderRadius: 17,
        backgroundColor: COLORS.BLACK,
        paddingVertical: 9,
        paddingHorizontal: 12,
    },
    defaultInviteText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        textAlign: 'center',
    },
    defaultInviteHintRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
    },
    defaultInviteHintPrefix: {
        ...FONTS.Title2,
        color: '#F4B6FF',
        marginRight: 8,
    },
    defaultInviteHintUser: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        maxWidth: '42%',
    },
    defaultInviteHintMovie: {
        ...FONTS.Title2,
        color: '#B8E8FF',
        flexShrink: 1,
        maxWidth: '48%',
        textAlign: 'left',
    },
    discoveryScreenWrap: {
        flex: 1,
    },
    discoveryScrollContent: {
        paddingBottom: 145,
    },
    discoveryBottomDock: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 15,
        paddingTop: 8,
        paddingBottom: Platform.OS === 'ios' ? 26 : 14,
        backgroundColor: COLORS.BLACK,
        borderTopWidth: 1,
        borderTopColor: 'rgba(95, 123, 255, 0.25)',
    },
    cinematicModalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    cinematicFullScreenLayer: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 64 : 36,
        justifyContent: 'center',
    },
    cinematicTitle: {
        ...FONTS.Title3,
        color: '#F6DDFF',
        textAlign: 'center',
    },
    cinematicStageText: {
        ...FONTS.Title2,
        color: '#B6D9FF',
        textAlign: 'center',
        marginTop: 4,
        marginBottom: 12,
    },
    cinematicMotionCanvas: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'flex-start',
        overflow: 'visible',
    },
    cinematicBurst: {
        position: 'absolute',
        left: 26,
        width: 0,
        height: 0,
        borderRadius: 46,
        backgroundColor: 'transparent',
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowRadius: 0,
        shadowOffset: {width: 0, height: 0},
        elevation: 0,
    },
    cinematicTrail: {
        position: 'absolute',
        left: 62,
        width: 230,
        height: 10,
        borderRadius: 8,
        backgroundColor: '#BD8BFF',
    },
    cinematicTicketWrap: {
        position: 'absolute',
        left: 0,
        top: 0,
        width: 122,
        height: 122,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cinematicTicketImage: {
        width: 112,
        height: 112,
        resizeMode: 'contain',
    },
    cinematicConfirmFloat: {
        position: 'absolute',
        left: 16,
        right: 16,
        bottom: Platform.OS === 'ios' ? 86 : 56,
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: 'rgba(16, 10, 45, 0.95)',
        borderWidth: 1,
        borderColor: 'rgba(110, 193, 255, 0.58)',
    },
    cinematicConfirmTitle: {
        ...FONTS.Title3,
        color: '#FFFFFF',
        textAlign: 'center',
    },
    cinematicConfirmSubtitle: {
        ...FONTS.paragraph2,
        color: '#B9CCFF',
        textAlign: 'center',
        marginTop: 3,
    },
});
