import { FONTS, COLORS, SIZES } from "./Theme";
import { AkcruLevels } from "../src/components";
import { LoremIpsum } from "lorem-ipsum";

const lorem = new LoremIpsum({
  sentencesPerParagraph: {
    max: 8,
    min: 4,
  },
  wordsPerSentence: {
    max: 8,
    min: 3,
  },
});

export const BADGES = [
  {
    badgeid: "guardian",
    label: "Guardian",
    color: "#ED54ED",
    bg: "#A620D740",
  },
  {
    badgeid: "hero",
    label: "Hero",
    color: "#F88163",
    bg: "#A7464040",
  },
  {
    badgeid: "superhero",
    label: "SuperHero",
    color: "#5689FF",
    bg: "#01003A40",
  },
  {
    badgeid: "ackruit",
    label: "Acrkuit",
    color: "#2FBFF1",
    bg: "#0A92C240",
  },
];

export const DIGITAL_PASS = [
  {
    GuardianPass:
      "https://akcru.com/wp-content/uploads/2023/05/GuardianCard.png",
    SuperHeroPass:
      "https://akcru.com/wp-content/uploads/2023/05/SuperHeroCard.png",
    HeroPass: "https://akcru.com/wp-content/uploads/2023/05/HeroCard.png",
    AkcruitPass: "https://akcru.com/wp-content/uploads/2023/05/AkcruitCard.png",
  },
];

export const AkcruDollarAmount = [
  {
    ADAmount: 46800,
  },
];

export const FAKE_AVATARS = [
  "https://media.istockphoto.com/id/1207856385/photo/joyful-happy-african-american-young-man-in-eyeglasses-portrait.jpg?s=612x612&w=0&k=20&c=M5sUFPE5xlF1fMxvNYgAqdpSZYKxSor3-SlF-o6IiJ0=",
  "https://images.unsplash.com/photo-1623184663110-89ba5b565eb6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
  "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
  "https://images.unsplash.com/photo-1522556189639-b150ed9c4330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
  "https://images.unsplash.com/photo-1603208636525-8825c33ed34b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
  "https://images.unsplash.com/photo-1562124638-724e13052daf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHNtaWxpbmclMjBtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
  "https://media.istockphoto.com/id/1353379051/photo/portrait-of-beautiful-mature-african-woman-looking-at-camera-outdoor.jpg?b=1&s=170667a&w=0&k=20&c=BZUbHXf0x6yAQiz6NX8gqauwEgrMlTQ0SqBI8qedH1g=",
  "https://media.istockphoto.com/id/1152603284/photo/african-woman-looking-at-camera.jpg?s=612x612&w=0&k=20&c=oAlZhgAkn0WmU3XClcbnNRNJh5Q19i4wVa-Qk8t_Mhc=",
  "https://img.freepik.com/free-photo/closeup-portrait-beautiful-smiling-brunette-model-trendy-girl-posing-street_158538-17019.jpg",
  "https://www.annettaapol.com/wp-content/uploads/2020/08/happy-woman-smiling.jpg",
  "https://images.unsplash.com/photo-1565148343401-5e4aa8f9c2cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8YmxhY2slMjBtYW4lMjBzbWlsZXxlbnwwfHwwfHw%3D&w=1000&q=80",
  "https://cdn.pixabay.com/photo/2014/09/25/22/14/profile-461076_960_720.jpg",
  "https://cdn.pixabay.com/photo/2015/01/15/13/06/woman-600238_960_720.jpg",
  "https://cdn.pixabay.com/photo/2022/12/24/21/14/portrait-7676482_960_720.jpg",
  "https://images.unsplash.com/photo-1551927636-1ea2a74bdc1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=398&q=80",
  "https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
  "https://images.unsplash.com/photo-1504199367641-aba8151af406?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1561505457-3bcad021f8ee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1521119989659-a83eee488004?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=423&q=80",
  "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
  "https://www.looktothestars.org/photo/11014-nia-long/story_half_width.jpg",
];

export const FAKE_USER_PROFILES = [
  {
    userName: "Jenny 2x",
    userPicture:
      "https://www.annettaapol.com/wp-content/uploads/2020/08/happy-woman-smiling.jpg",
    userDesc:
      "My name is Jenny 2x, cause I like to watch movies 2x's lol, #moviebuff #akcrurecruiter",
    userFollowerAmount: 12501,
    akcruBadge: { superhero: true },
    ADAmount: 46820,
    userMITAmount: 3,
    movieReview: lorem.generateSentences(6),
    movieReviewDate: "1/20/2023",
    crummunityPost: lorem.generateSentences(1),
    CrummunityFeedPostLikes: 7,
    Crummunityreplies: "",
    CRUChat: lorem.generateSentences(2),
    CruChatTime: "9:30 AM",
    CruChatDate: "9/20/2023",
    CRUName: "Jenny 2x Cru",
    userID: "0",
    status: "Watching 'Avengers'",
    privateaccount: false,
    online: true,
    USDtoAkcruDollar: false,
    influencer: false,
    digitalpass:
      "https://akcru.com/wp-content/uploads/2023/05/SuperHeroCard.png",
    host: true,
  },
  {
    userName: "Anthoni Styvens",
    userPicture:
      "https://images.unsplash.com/photo-1521119989659-a83eee488004?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=423&q=80",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { guardian: true },
    ADAmount: 345700,
    userMITAmount: 0,
    movieReview: lorem.generateSentences(5),
    movieReviewDate: "12/1/2023",
    crummunityPost: lorem.generateSentences(2),
    CrummunityFeedPostLikes: 200,
    Crummunityreplies: "View 20 replies",
    CRUChat: lorem.generateSentences(1),
    CruChatTime: "9:35 AM",
    CruChatDate: "9/20/2023",
    CRUName: "Apex CRU",
    userID: "1",
    status: "Watching 'Top Gun Maverick'",
    privateaccount: false,
    online: false,
    USDtoAkcruDollar: true,
    influencer: false,
    digitalpass:
      "https://akcru.com/wp-content/uploads/2023/05/GuardianCard.png",
    host: false,
  },
  {
    userName: "Jessie's Girl",
    userPicture:
      "https://cdn.pixabay.com/photo/2015/01/15/13/06/woman-600238_960_720.jpg",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 1131,
    akcruBadge: { hero: true },
    ADAmount: 5700,
    userMITAmount: 1,
    movieReview: lorem.generateSentences(3),
    movieReviewDate: "8/3/2023",
    crummunityPost: lorem.generateSentences(2),
    CrummunityFeedPostLikes: 27,
    Crummunityreplies: "View 3 replies",
    CRUChat: lorem.generateSentences(2),
    CruChatTime: "9:40 AM",
    CruChatDate: "9/20/2023",
    CRUName: "Jessie's CRU",
    userID: "2",
    status: "Watching 'Avengers'",
    privateaccount: false,
    online: false,
    USDtoAkcruDollar: true,
    influencer: false,
    digitalpass: "https://akcru.com/wp-content/uploads/2023/05/HeroCard.png",
    host: false,
  },
  {
    userName: "IronClad Chad",
    userPicture:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    userDesc: lorem.generateSentences(2),
    userFollowerAmount: 45231,
    akcruBadge: { akcruit: true },
    ADAmount: 3409,
    userMITAmount: 2,
    movieReview: lorem.generateSentences(5),
    movieReviewDate: "10/2/2023",
    crummunityPost: lorem.generateSentences(2),
    CrummunityFeedPostLikes: 92,
    Crummunityreplies: "",
    CRUChat: lorem.generateSentences(2),
    CruChatTime: "9:30 AM",
    CruChatDate: "9/21/2023",
    CRUName: "IronClad CRU",
    userID: "3",
    status: "Watching 'Avengers'",
    privateaccount: false,
    online: true,
    USDtoAkcruDollar: true,
    influencer: false,
    digitalpass: "https://akcru.com/wp-content/uploads/2023/05/AkcruitCard.png",
    host: false,
  },
  {
    userName: "Movie Queen",
    userPicture:
      "https://images.unsplash.com/photo-1551927636-1ea2a74bdc1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=398&q=80",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { superhero: true },
    ADAmount: 5700,
    userMITAmount: 2,
    movieReview: lorem.generateSentences(7),
    movieReviewDate: "11/22/2023",
    crummunityPost: lorem.generateSentences(1),
    CrummunityFeedPostLikes: 105,
    Crummunityreplies: "",
    CRUChat: lorem.generateSentences(1),
    CruChatTime: "9:40 AM",
    CruChatDate: "9/21/2023",
    CRUName: "Queen CRU",
    userID: "4",
    status: "Watching 'Avengers'",
    privateaccount: false,
    online: true,
    USDtoAkcruDollar: true,
    influencer: false,
    digitalpass:
      "https://akcru.com/wp-content/uploads/2023/05/SuperHeroCard.png",
    host: false,
  },
  {
    userName: "Def Jeff",
    userPicture:
      "https://images.unsplash.com/photo-1623184663110-89ba5b565eb6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    userDesc: lorem.generateSentences(2),
    userFollowerAmount: 110231,
    akcruBadge: { hero: true },
    ADAmount: 4457,
    userMITAmount: 3,
    movieReview: lorem.generateSentences(4),
    movieReviewDate: "12/25/2022",
    crummunityPost: lorem.generateSentences(1),
    CrummunityFeedPostLikes: 75,
    Crummunityreplies: "View 5 replies",
    CRUChat: lorem.generateSentences(1),
    CruChatTime: "9:45 AM",
    CruChatDate: "9/21/2023",
    CRUName: "Def Jeff CRU",
    userID: "5",
    status: "Watching 'Avengers'",
    privateaccount: true,
    online: true,
    USDtoAkcruDollar: true,
    influencer: false,
    digitalpass: "https://akcru.com/wp-content/uploads/2023/05/HeroCard.png",
    host: false,
  },
  {
    userName: "Stella's Groove",
    userPicture:
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { guardian: true },
    ADAmount: 23567,
    userMITAmount: 0,
    movieReview: lorem.generateSentences(8),
    movieReviewDate: "1/2/2023",
    crummunityPost: lorem.generateSentences(3),
    CrummunityFeedPostLikes: 25,
    Crummunityreplies: "",
    CRUChat: lorem.generateSentences(1),
    CruChatTime: "10:30 AM",
    CruChatDate: "9/21/2023",
    CRUName: "Groovy CRU",
    userID: "6",
    status: "Watching 'Avengers'",
    privateaccount: false,
    online: true,
    USDtoAkcruDollar: false,
    influencer: false,
    digitalpass:
      "https://akcru.com/wp-content/uploads/2023/05/GuardianCard.png",
    host: false,
  },
  {
    userName: "Nia Long",
    userPicture:
      "https://www.looktothestars.org/photo/11014-nia-long/story_half_width.jpg",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { guardian: true },
    ADAmount: 150985,
    userMITAmount: 7,
    movieReview: lorem.generateSentences(8),
    movieReviewDate: "1/6/2023",
    crummunityPost: lorem.generateSentences(3),
    CrummunityFeedPostLikes: 506,
    Crummunityreplies: "View 20 replies",
    CRUChat: lorem.generateSentences(1),
    CruChatTime: "10:20 AM",
    CruChatDate: "9/22/2023",
    CRUName: "Long Foundation CRU",
    userID: "7",
    status: "Best Man Holiday",
    privateaccount: false,
    online: true,
    USDtoAkcruDollar: false,
    influencer: true,
    digitalpass:
      "https://akcru.com/wp-content/uploads/2023/05/GuardianCard.png",
    host: false,
  },
];

export const AKCRUAPP_TOTAL_AD = [
  {
    akcruTotalADAmount: 58646770,
    percentageChange: 7,
  },
];

export const JENNY_SCHEDULE = [
  {
    movieName: "Whiplash",
    moviePoster:
      "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    movieYear: 2014,
    length: "1h 46m",
    movieRated: "R",
    movieGenre: "Drama",
    movieRating: 8.5,
    scheduleType: { MIT: true, CRUView: false },
    scheduleDate: "11/2/2023",
    scheduleTime: "7:30 PM",
    scheduleWith: "Anthoni Styvens",
    dateID: "0",
  },
  {
    movieName: "Warrior",
    moviePoster:
      "https://m.media-amazon.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_.jpg",
    movieYear: 2011,
    length: "2h 20m",
    movieRated: "PG-13",
    movieGenre: "Action",
    movieRating: 8.2,
    scheduleType: { MIT: false, CRUView: true },
    scheduleDate: "10/30/2023",
    scheduleTime: "9:00 PM",
    scheduleWith: "",
    dateID: "1",
  },
  {
    movieName: "WALL-E",
    moviePoster:
      "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_.jpg",
    movieYear: 2008,
    length: "1h 38m",
    movieRated: "G",
    movieGenre: "Animation",
    movieRating: 8.4,
    scheduleType: { MIT: true, CRUView: false },
    scheduleDate: "11/1/2023",
    scheduleTime: "6:45 PM",
    scheduleWith: "Jessie's Girl",
    dateID: "2",
  },
  {
    movieName: "V for Vendetta",
    moviePoster:
      "https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_.jpg",
    movieYear: 2006,
    length: "2h 12m",
    movieRated: "R",
    movieGenre: "Action",
    movieRating: 8.2,
    scheduleType: { MIT: true, CRUView: false },
    scheduleDate: "10/28/2023",
    scheduleTime: "7:00 PM",
    scheduleWith: "Jimmy Conway",
    dateID: "3",
  },
  {
    movieName: "There Will Be Blood",
    moviePoster:
      "https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_.jpg",
    movieYear: 2008,
    length: "2h 38m",
    movieRated: "R",
    movieGenre: "Drama",
    movieRating: 8.2,
    scheduleType: { MIT: false, CRUView: true },
    scheduleDate: "10/30/2023",
    scheduleTime: "6:00 PM",
    scheduleWith: "",
    dateID: "4",
  },
];

export const JENNY_INVITES = [
  {
    inviteeName: "Jerry Loves Movies",
    inviteePicture:
      "https://media.istockphoto.com/id/1152603284/photo/african-woman-looking-at-camera.jpg?s=612x612&w=0&k=20&c=oAlZhgAkn0WmU3XClcbnNRNJh5Q19i4wVa-Qk8t_Mhc=",
    inviteDate: "11/20/2023",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 23900,
    akcruBadge: { hero: true },
    ADAmount: 23567,
    status: "Watching 'Avengers'",
    userMITAmount: 7,
    MITID: "0",
    influencer: false,
    privateaccount: false,
    online: true,
    MITMoviechoice: "V for Vendetta",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_.jpg",
    MITDate: "11/1/2023",
    MITTime: "9:30 PM",
  },
  {
    inviteeName: "Jessie",
    inviteePicture:
      "https://media.istockphoto.com/id/1207856385/photo/joyful-happy-african-american-young-man-in-eyeglasses-portrait.jpg?s=612x612&w=0&k=20&c=M5sUFPE5xlF1fMxvNYgAqdpSZYKxSor3-SlF-o6IiJ0=",
    inviteDate: "11/10/2023",
    userDesc: lorem.generateSentences(2),
    userFollowerAmount: 110231,
    akcruBadge: { akcruit: true },
    ADAmount: 150985,
    status: "Watching 'Avengers'",
    userMITAmount: 7,
    MITID: "1",
    influencer: false,
    privateaccount: false,
    online: true,
    MITMoviechoice: "Unforgiven",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BODM3YWY4NmQtN2Y3Ni00OTg0LWFhZGQtZWE3ZWY4MTJlOWU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    MITDate: "11/2/2023",
    MITTime: "9:50 PM",
  },
  {
    inviteeName: "Mooo-Vee",
    inviteePicture:
      "https://images.unsplash.com/photo-1623184663110-89ba5b565eb6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    inviteDate: "10/28/2023",
    userDesc: lorem.generateSentences(3),
    userFollowerAmount: 2351,
    akcruBadge: { guardian: true },
    ADAmount: 8235675,
    status: "Watching 'Avengers'",
    userMITAmount: 7,
    MITID: "2",
    influencer: true,
    privateaccount: false,
    online: false,
    MITMoviechoice: "Up",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_.jpg",
    MITDate: "10/29/2023",
    MITTime: "7:30 PM",
  },
  {
    inviteeName: "Sex, Drugs, and Movies",
    inviteePicture:
      "https://images.unsplash.com/photo-1562124638-724e13052daf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHNtaWxpbmclMjBtYW58ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    inviteDate: "9/29/2023",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { superhero: true },
    ADAmount: 150985,
    status: "Best Man Holiday",
    userMITAmount: 7,
    MITID: "3",
    influencer: false,
    privateaccount: false,
    online: true,
    MITMoviechoice: "Top Gun: Maverick",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
    MITDate: "10/1/2023",
    MITTime: "8:00 PM",
  },
  {
    inviteeName: "Queen Alexandra",
    inviteePicture:
      "https://images.unsplash.com/photo-1603208636525-8825c33ed34b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c21pbGluZyUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    inviteDate: "11/23/2023",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 110231,
    akcruBadge: { akcruit: true },
    ADAmount: 150985,
    status: "Watching 'Avengers'",
    userMITAmount: 7,
    MITID: "4",
    influencer: false,
    privateaccount: false,
    online: true,
    MITMoviechoice: "To Kill a Mockingbird",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BNmVmYzcwNzMtMWM1NS00MWIyLThlMDEtYzUwZDgzODE1NmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    MITDate: "10/1/2023",
    MITTime: "10:00 PM",
  },
  {
    inviteeName: "Cool Chad",
    inviteePicture:
      "https://images.unsplash.com/photo-1561505457-3bcad021f8ee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
    inviteDate: "11/20/2023",
    userDesc: lorem.generateSentences(2),
    userFollowerAmount: 231,
    akcruBadge: { superhero: true },
    ADAmount: 50985,
    status: "Best Man Holiday",
    userMITAmount: 7,
    MITID: "5",
    influencer: false,
    privateaccount: false,
    online: false,
    MITMoviechoice: "There Will Be Blood",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_.jpg",
    MITDate: "11/18/2023",
    MITTime: "9:50 PM",
  },
  {
    inviteeName: "Brook",
    inviteePicture:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
    inviteDate: "11/10/2023",
    userDesc: lorem.generateSentences(1),
    userFollowerAmount: 1231,
    akcruBadge: { hero: true },
    ADAmount: 1585,
    status: "Watching 'Avengers'",
    userMITAmount: 7,
    MITID: "6",
    influencer: false,
    privateaccount: false,
    online: true,
    MITMoviechoice: "The Wolf of Wall Street",
    MITMovieposter:
      "https://m.media-amazon.com/images/M/MV5BNjUyMTc4MDExMV5BMl5BanBnXkFtZTgwNDg0NDIwMjE@._V1_.jpg",
    MITDate: "11/20/2023",
    MITTime: "9:00 PM",
  },
];
