import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../assets/constants';
import { isTablet } from '../../../assets/constants/theme';

export default StyleSheet.create({
    topContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginHorizontal: 15,
    },
    post: {
        ...FONTS.paragraph2,
        lineHeight: 18,
    },
    footStats: {
        ...FONTS.paragraph1,
        lineHeight: 18,
        color: COLORS.AKCRUBLUE,
        opacity: 0.5,
        paddingTop: 3,
    },
    cardcontainer: {
        borderRadius: 14,
        overflow: 'hidden',
    },
    cardInner: {
        backgroundColor: '#0a0a12',
        borderRadius: 12,
        padding: 14,
    },
    gradientFrame: {
        borderRadius: 14,
        padding: 2,
    },
    displayName: {
        ...FONTS.Username,
        color: COLORS.WHITE,
        fontWeight: '700',
        fontSize: isTablet() ? 18 : 15,
    },
    handleText: {
        ...FONTS.paragraph1,
        color: 'rgba(255,255,255,0.45)',
        fontSize: isTablet() ? 15 : 14,
        marginTop: 2,
    },
    followBtn: {
        backgroundColor: 'rgba(155, 89, 182, 0.35)',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(155, 89, 182, 0.7)',
    },
    followBtnText: {
        color: COLORS.WHITE,
        fontSize: 13,
        fontWeight: '600',
    },
    headline: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        fontWeight: '700',
        marginTop: 8,
        lineHeight: 22,
    },
    descText: {
        ...FONTS.paragraph1,
        color: 'rgba(255,255,255,0.55)',
        marginTop: 6,
        lineHeight: 20,
    },
    tagPill: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 8,
        marginTop: 10,
    },
    tagText: {
        color: COLORS.WHITE,
        fontSize: 13,
        marginLeft: 4,
    },
    engagementRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
        marginTop: 18,
        paddingVertical: 8,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: 'rgba(155, 89, 182, 0.25)',
    },
    engagementLabel: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 12,
        marginTop: 6,
        textAlign: 'center',
    },
    commentBar: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 24,
        backgroundColor: '#12121c',
        borderWidth: 1,
        borderColor: '#9b59b6',
    },
    commentPlaceholder: {
        flex: 1,
        color: 'rgba(255,255,255,0.4)',
        fontSize: 15,
    },
    mediaImage: {
        width: '100%',
        aspectRatio: 4 / 5,
        marginTop: 12,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        borderBottomLeftRadius: 8,
        borderBottomRightRadius: 8,
        alignSelf: 'center',
    },
    stamps: {
        ...FONTS.Title2Orange,
        marginBottom: 3,
    },
    stamps2: {
        ...FONTS.Title2AkcruBlue,
        fontSize: 14,
        color: COLORS.LIGHTGREY,
    },
    reply: {
        ...FONTS.Title1,
        color: COLORS.AKCRUBLUE,
        fontSize: 14,
    },
    viewreply: {
        ...FONTS.Title1,
        color: COLORS.CATPURPLGT,
        fontSize: 14,
    },
    postimage: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 10,
        marginTop: 10,
    },
    postvideo: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 10,
        marginTop: 10,
    },
    postfooter: {
        marginTop: 20,
        width: isTablet() ? '15%' : SIZES.ScreenWidth / 5,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    postfooterside: {
        justifyContent: 'space-between',
    },
    postoptionsmodal: {
        width: '100%',
        backgroundColor: COLORS.AKCRUBACKGROUND,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        padding: 15,
    },
    postoptioncontainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    videoStyle: {width: '100%', height: '100%', borderRadius: 0},
});
