import {StyleSheet} from 'react-native';
import {COLORS, FONTS, SIZES} from '../../../../assets/constants';
import {isTablet} from '../../../../assets/constants/theme';

const videoCardSize = Math.min(SIZES.ScreenWidth - 48, 340);
const contentWidth = Math.min(SIZES.ScreenWidth - 48, 340);

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 4,
    },
    backButton: {
        width: 40,
        height: 40,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    headerSpacer: {
        width: 40,
    },
    headerTitle: {
        flex: 1,
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 16 : 14,
        color: COLORS.AKCRUBLUE,
        letterSpacing: 1.2,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 24,
        paddingTop: isTablet() ? 24 : 16,
        paddingBottom: 32,
        alignItems: 'center',
    },
    movieTitle: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 42 : 36,
        color: COLORS.WHITE,
        letterSpacing: 2,
        textTransform: 'uppercase',
        textAlign: 'center',
    },
    filmBy: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        marginTop: 8,
        textAlign: 'center',
    },
    badge: {
        marginTop: 16,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: COLORS.AKCRUBLUE,
    },
    badgeText: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 12 : 11,
        color: COLORS.BLACK,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    videoSection: {
        width: '100%',
        alignItems: 'center',
        marginTop: 24,
    },
    videoCard: {
        width: videoCardSize,
        height: videoCardSize,
        aspectRatio: 1,
        borderRadius: 12,
        overflow: 'hidden',
        alignSelf: 'center',
        backgroundColor: COLORS.DARKERGREY,
    },
    videoThumbnail: {
        width: videoCardSize,
        height: videoCardSize,
        aspectRatio: 1,
    },
    playOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.OVERLAY_BLACK_35,
    },
    playControls: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    playIconCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        borderWidth: 2,
        borderColor: COLORS.AKCRUBLUE,
        backgroundColor: COLORS.OVERLAY_BLACK_50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    watchTrailerLabel: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginTop: 10,
        letterSpacing: 1,
        textTransform: 'uppercase',
        textAlign: 'center',
    },
    metaRow: {
        width: contentWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    metaText: {
        ...FONTS.paragraph2,
        color: COLORS.LIGHTGREY,
        flex: 1,
        marginRight: 12,
    },
    ratingBox: {
        width: 28,
        height: 28,
        borderWidth: 1.5,
        borderColor: COLORS.WHITE,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ratingText: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 14,
        color: COLORS.WHITE,
    },
    synopsis: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        width: contentWidth,
        marginTop: 20,
        lineHeight: isTablet() ? 24 : 22,
    },
    synopsisSecondary: {
        ...FONTS.paragraph2,
        color: COLORS.LIGHTGREY,
        width: contentWidth,
        marginTop: 12,
        lineHeight: isTablet() ? 24 : 22,
    },
    screeningBox: {
        width: contentWidth,
        marginTop: 24,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderRadius: 12,
        backgroundColor: COLORS.DARKERGREY,
    },
    screeningHeading: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 13 : 12,
        color: COLORS.AKCRUBLUE,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    screeningDates: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginTop: 8,
        lineHeight: isTablet() ? 22 : 20,
    },
    accessButton: {
        width: contentWidth,
        height: isTablet() ? 52 : 48,
        borderRadius: 10,
        backgroundColor: COLORS.AKCRUBLUE,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 28,
    },
    accessButtonLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 15 : 13,
        color: COLORS.WHITE,
        letterSpacing: 0.8,
    },
});
