import {StyleSheet} from 'react-native';
import {COLORS, FONTS} from '../../../../assets/constants';
import {isTablet} from '../../../../assets/constants/theme';

const contentHorizontal = 20;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    screenBody: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 16,
    },
    bottomFooter: {
        paddingHorizontal: contentHorizontal,
        paddingTop: 12,
        paddingBottom: isTablet() ? 20 : 16,
        backgroundColor: COLORS.BLACK,
        gap: 12,
    },
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: contentHorizontal,
        paddingTop: 8,
        paddingBottom: 8,
    },
    headerIconButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    heroWrap: {
        width: '100%',
        position: 'relative',
        backgroundColor: COLORS.BLACK,
    },
    heroTitleOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 16,
        paddingHorizontal: contentHorizontal,
        alignItems: 'flex-start',
    },
    contentBlock: {
        paddingHorizontal: contentHorizontal,
        paddingTop: 18,
        alignItems: 'flex-start',
        alignSelf: 'stretch',
    },
    watchTrailerButton: {
        width: '100%',
        height: isTablet() ? 50 : 46,
        borderRadius: 6,
        borderWidth: 1.5,
        borderColor: COLORS.OVERLAY_WHITE_40,
        backgroundColor: COLORS.BLACK,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    watchTrailerButtonDisabled: {
        opacity: 0.45,
    },
    watchTrailerLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 14 : 12,
        color: COLORS.WHITE,
        letterSpacing: 1.4,
    },
    exclusiveLabel: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 12 : 11,
        color: COLORS.WHITE,
        letterSpacing: 1,
        textTransform: 'uppercase',
        textAlign: 'left',
        marginTop: 14,
        alignSelf: 'stretch',
    },
    metaText: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 13 : 12,
        color: COLORS.WHITE,
        letterSpacing: 0.6,
        textTransform: 'uppercase',
        textAlign: 'left',
        marginTop: 10,
        alignSelf: 'stretch',
    },
    synopsis: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 15 : 14,
        color: COLORS.WHITE,
        lineHeight: isTablet() ? 24 : 22,
        marginTop: 18,
        textAlign: 'left',
        alignSelf: 'stretch',
    },
    creditBlock: {
        marginTop: 18,
        alignSelf: 'stretch',
    },
    creditLabel: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 11 : 10,
        color: COLORS.OVERLAY_WHITE_45,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: 4,
    },
    creditValue: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 14 : 13,
        color: COLORS.WHITE,
        lineHeight: isTablet() ? 22 : 20,
    },
    screeningBox: {
        alignSelf: 'stretch',
        paddingHorizontal: 14,
        paddingVertical: 14,
        borderRadius: 8,
        borderWidth: 1.5,
        borderColor: COLORS.CATREDLGT,
        backgroundColor: 'rgba(70,0,0,0.35)',
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    screeningIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: 'rgba(173,7,7,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
    },
    screeningCopy: {
        flex: 1,
    },
    screeningHeading: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 12 : 11,
        color: COLORS.CATREDLGT,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    screeningDates: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 13 : 12,
        color: COLORS.WHITE,
        marginTop: 6,
        lineHeight: isTablet() ? 20 : 18,
    },
    screeningEventLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 12 : 11,
        color: COLORS.WHITE,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        marginTop: 8,
    },
    accessButton: {
        width: '100%',
        height: isTablet() ? 52 : 48,
        borderRadius: 8,
        backgroundColor: COLORS.CATREDLGT,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    accessButtonDisabled: {
        opacity: 0.45,
    },
    accessButtonLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 15 : 13,
        color: COLORS.WHITE,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
});
