import {StyleSheet} from 'react-native';
import {COLORS, FONTS} from '../../../../assets/constants';
import {isTablet} from '../../../../assets/constants/theme';

const contentHorizontal = 20;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    screenBody: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: contentHorizontal,
        paddingBottom: 16,
    },
    title: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 22 : 18,
        color: COLORS.WHITE,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        textAlign: 'center',
        marginTop: 8,
    },
    subtitle: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 14 : 13,
        color: COLORS.OVERLAY_WHITE_70,
        lineHeight: isTablet() ? 22 : 20,
        textAlign: 'center',
        marginTop: 12,
        paddingHorizontal: 8,
    },
    creatorCard: {
        width: '100%',
        aspectRatio: 0.82,
        borderRadius: 10,
        overflow: 'hidden',
        marginTop: 24,
        backgroundColor: COLORS.OVERLAY_WHITE_10,
    },
    creatorImage: {
        width: '100%',
        height: '100%',
    },
    creatorImageBottomShadow: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '52%',
    },
    creatorOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingVertical: 16,
        zIndex: 2,
    },
    creatorName: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 16 : 14,
        color: COLORS.WHITE,
        letterSpacing: 0.6,
    },
    creatorRole: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 13 : 12,
        color: COLORS.OVERLAY_WHITE_70,
        marginTop: 4,
    },
    sectionHeading: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 13 : 12,
        color: COLORS.CATREDLGT,
        letterSpacing: 1.4,
        textTransform: 'uppercase',
        textAlign: 'center',
        marginTop: 28,
        marginBottom: 14,
    },
    connectList: {
        gap: 10,
    },
    castSection: {
        gap: 10,
    },
    castSectionLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 11 : 10,
        color: COLORS.OVERLAY_WHITE_45,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    connectRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.OVERLAY_WHITE_20,
        backgroundColor: 'rgba(255,255,255,0.04)',
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 12,
    },
    connectAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.OVERLAY_WHITE_10,
    },
    connectAvatarFallback: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.CATREDLGT,
        alignItems: 'center',
        justifyContent: 'center',
    },
    connectAvatarFallbackLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 14,
        color: COLORS.WHITE,
    },
    connectCopy: {
        flex: 1,
    },
    connectTitle: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 14 : 13,
        color: COLORS.WHITE,
        letterSpacing: 0.6,
        textTransform: 'uppercase',
    },
    connectSubtitle: {
        ...FONTS.paragraph2,
        fontSize: isTablet() ? 12 : 11,
        color: COLORS.OVERLAY_WHITE_45,
        marginTop: 2,
    },
    bottomFooter: {
        paddingHorizontal: contentHorizontal,
        paddingTop: 12,
        paddingBottom: isTablet() ? 20 : 16,
        backgroundColor: COLORS.BLACK,
        borderTopWidth: 1,
        borderTopColor: COLORS.OVERLAY_WHITE_20,
        gap: 10,
    },
    joinAkruPrompt: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 15 : 14,
        color: COLORS.WHITE,
        textAlign: 'left',
        alignSelf: 'stretch',
        textDecorationLine: 'underline',
        textDecorationColor: COLORS.WHITE,
        letterSpacing: 0.4,
    },
    homeButton: {
        width: '100%',
        height: isTablet() ? 52 : 48,
        borderRadius: 8,
        backgroundColor: COLORS.CATREDLGT,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeButtonLabel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: isTablet() ? 15 : 13,
        color: COLORS.WHITE,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
});
