import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

const MIT_COMBINED_CARD_HEIGHT = 120;
const MIT_COMBINED_CARD_RADIUS = 16;
const COUNTDOWN_RING_SIZE = Math.min(Math.max(SIZES.ScreenWidth * 0.74, 252), 300);
const COUNTDOWN_RING_RADIUS = COUNTDOWN_RING_SIZE / 2;
const COUNTDOWN_RING_THICKNESS = 2;
const COUNTDOWN_SPIN_RADIUS = COUNTDOWN_RING_RADIUS - COUNTDOWN_RING_THICKNESS;
const COUNTDOWN_GLOW_SIZE = COUNTDOWN_RING_SIZE + 18;

export default StyleSheet.create({
    acceptedScreenContainer: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    acceptedGlowBackground: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 0,
    },
    fogOrb: {
        position: 'absolute',
        backgroundColor: 'rgba(255,255,255,0.22)',
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.35)',
    },
    acceptedScrollContent: {
        flexGrow: 1,
        backgroundColor: 'transparent',
    },
    acceptedInnerContent: {
        paddingHorizontal: 14,
    },
    acceptedTopArea: {
        marginTop: 4,
    },
    acceptedHeaderImage: {
        width: 170,
        height: 102,
        alignSelf: 'center',
        marginTop: 6,
        marginBottom: 4,
    },
    acceptedTitle: {
        ...FONTS.Title1,
        color: COLORS.WHITE,
        textAlign: 'center',
        marginTop: 10,
    },
    acceptedSubtitle: {
        ...FONTS.paragraph1,
        color: 'rgba(241,223,255,0.92)',
        textAlign: 'center',
        marginTop: 6,
    },
    acceptedCardWrap: {
        marginTop: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(199,147,255,0.55)',
        backgroundColor: 'rgba(23, 8, 35, 0.72)',
        padding: 10,
        shadowColor: '#B86DFF',
        shadowOpacity: 0.45,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: 0},
        elevation: 10,
    },
    acceptedInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    acceptedInfoBody: {
        marginLeft: 10,
        flex: 1,
    },
    acceptedInfoTitle: {
        ...FONTS.Title2,
        color: '#F3E7FF',
    },
    acceptedInfoMeta: {
        ...FONTS.paragraph2,
        color: 'rgba(236,221,255,0.92)',
        marginTop: 2,
    },
    acceptedSessionText: {
        ...FONTS.paragraph2,
        color: '#8CFFB5',
        marginTop: 4,
    },
    acceptedChatButton: {
        width: '100%',
        alignSelf: 'center',
        marginTop: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(214,150,255,0.78)',
        backgroundColor: 'rgba(168, 85, 255, 0.34)',
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    acceptedChatButtonText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    acceptedChatHint: {
        ...FONTS.paragraph2,
        color: 'rgba(232,211,255,0.9)',
        marginTop: 2,
    },
    acceptedSmoothText: {
        ...FONTS.Title2,
        color: 'rgba(235,216,255,0.95)',
        textAlign: 'center',
        marginTop: 18,
        marginBottom: 8,
    },
    acceptedPromptList: {
        width: '100%',
    },
    acceptedPromptChip: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(206, 155, 255, 0.7)',
        backgroundColor: 'rgba(48, 18, 74, 0.55)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 8,
    },
    acceptedPromptText: {
        ...FONTS.paragraph2,
        color: '#F1E6FF',
    },
    acceptedBottomComposer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 0,
        paddingTop: 8,
        backgroundColor: 'rgba(11,4,18,0.95)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(191,146,255,0.35)',
    },
    acceptedComposerTopRow: {
        marginBottom: 6,
    },
    acceptedComposerTimeText: {
        ...FONTS.paragraph2,
        color: '#E7D5FF',
    },
    acceptedComposerInputRow: {
        position: 'relative',
        width: '100%',
        borderWidth: 0,
        borderRadius: 0,
        backgroundColor: 'transparent',
        minHeight: 42,
        paddingLeft: 0,
        paddingRight: 52,
        flexDirection: 'row',
        alignItems: 'center',
    },
    acceptedComposerInput: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        width: '100%',
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    acceptedComposerSend: {
        position: 'absolute',
        right: 14,
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: 'rgba(132,76,255,0.9)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    declinedTopWrap: {
        marginTop: 10,
        alignItems: 'center',
    },
    declinedTitle: {
        ...FONTS.Title1,
        color: '#F3E9FF',
        textAlign: 'center',
    },
    declinedSubtitle: {
        ...FONTS.paragraph1,
        color: 'rgba(231,214,255,0.9)',
        textAlign: 'center',
        marginTop: 4,
    },
    declinedPrimaryCta: {
        width: '100%',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(214,150,255,0.78)',
        backgroundColor: 'rgba(168, 85, 255, 0.34)',
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 14,
    },
    declinedPrimaryTitle: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    declinedPrimarySub: {
        ...FONTS.paragraph2,
        color: 'rgba(232,211,255,0.9)',
        marginTop: 2,
    },
    declinedSecondaryCta: {
        width: '100%',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(175, 149, 225, 0.72)',
        backgroundColor: 'rgba(40, 26, 74, 0.62)',
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 12,
    },
    declinedSecondaryTitle: {
        ...FONTS.Title2,
        color: '#F4ECFF',
    },
    declinedSecondarySub: {
        ...FONTS.paragraph2,
        color: 'rgba(228,213,249,0.9)',
        marginTop: 2,
    },
    declinedUnlockCard: {
        width: '100%',
        marginTop: 0,
        borderRadius: 14,
        borderWidth: 0,
        backgroundColor: 'rgba(10, 10, 14, 0.9)',
        paddingVertical: 14,
        paddingHorizontal: 12,
    },
    declinedUnlockCardBorder: {
        width: '100%',
        marginTop: 12,
        borderRadius: 14,
        padding: 1,
    },
    declinedUnlockTitle: {
        ...FONTS.Title2,
        color: '#F5EDFF',
    },
    declinedUnlockSub: {
        ...FONTS.paragraph2,
        color: 'rgba(230,214,250,0.92)',
        marginTop: 4,
    },
    declinedUnlockButton: {
        marginTop: 10,
        alignSelf: 'center',
        minWidth: 170,
        borderRadius: 10,
        backgroundColor: '#4C63FF',
        paddingVertical: 9,
        paddingHorizontal: 20,
    },
    declinedUnlockButtonText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        textAlign: 'center',
    },
    declinedTipCard: {
        width: '100%',
        marginTop: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(156,130,213,0.7)',
        backgroundColor: 'rgba(45, 27, 84, 0.6)',
        paddingVertical: 12,
        paddingHorizontal: 12,
    },
    declinedTipTitle: {
        ...FONTS.Title2,
        color: '#F4ECFF',
    },
    declinedTipText: {
        ...FONTS.paragraph2,
        color: 'rgba(231,216,252,0.94)',
        marginTop: 2,
    },
    declinedBackToFeedWrap: {
        marginTop: 18,
        marginBottom: 10,
        width: '100%',
    },
    declinedBackDividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
    },
    declinedBackDividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: 'rgba(236, 231, 246, 0.35)',
    },
    declinedBackToFeed: {
        ...FONTS.Title2,
        color: 'rgba(236, 231, 246, 0.9)',
        textAlign: 'center',
        marginHorizontal: 10,
    },
    declinedPinnedActionsWrap: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 14,
        paddingTop: 10,
        backgroundColor: '#000000',
        borderTopWidth: 0,
        elevation: 0,
        shadowOpacity: 0,
    },
    hiddenSection: {
        display: 'none',
    },
    topcontainer: {
        marginTop: 46,
        marginHorizontal: 15,
    },
    bottomcontainer: {
        marginHorizontal: 15,
        marginTop: -10,
    },
    poster: {width: 85, height: 115, borderRadius: 5},
    datebox: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.BLACK,
        borderRadius: 5,
        padding: 15,
    },
    datetext: {
        ...FONTS.Title2,
        color: COLORS.LIGHTGREY,
    },
    inviteStatusRow: {
        ...FONTS.Title2,
        textAlign: 'center',
        marginTop: 8,
        letterSpacing: 0.5,
    },
    inviteStatusPrefix: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    inviteStatusValue: {
        ...FONTS.Title2,
        color: COLORS.STARGOLD,
    },
    inviteStatusSubtext: {
        ...FONTS.paragraph1,
        color: COLORS.WHITE,
        textAlign: 'center',
        marginTop: 4,
        paddingHorizontal: 12,
    },
    sheetcontainer: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    screenGlowBackground: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 0,
    },
    chooseMitScroll: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitScrollContent: {
        paddingBottom: 16,
        flexGrow: 1,
        backgroundColor: COLORS.BLACK,
    },
    pendingScreenContainer: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    pendingScreenScrollContent: {
        flexGrow: 1,
        backgroundColor: COLORS.BLACK,
    },
    pendingHorizontalInset: {
        marginHorizontal: 14,
    },
    chooseMitBottomBar: {
        backgroundColor: 'transparent',
        paddingTop: 0,
        position: 'absolute',
        top: 70,
        left: 0,
        right: 0,
        zIndex: 20,
    },
    swipeSectionRaised: {
        marginTop: 0,
    },
    sheetview: {},
    opensheet: {
        height: SIZES.ScreenHeight * 0.2,
        backgroundColor: COLORS.TAGCOLOR,
        padding: 10,
    },
    input: {
        flexDirection: 'row',
        borderWidth: 0.8,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        justifyContent: 'space-between',
        marginVertical: 10,
        paddingLeft: 10,
        alignContent: 'center',
        height: 40,
        alignItems: 'center',
    },
    textinput: {
        color: COLORS.LIGHTGREY,
        width: '100%',
        flex: 1,
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    playButton: {
        ...FONTS.Title2,
    },
    activitycontainer: {
        height: SIZES.ScreenHeight,
        width: SIZES.ScreenWidth,
        justifyContent: 'center',
    },
    postcontainer: {
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        marginBottom: 5,
    },
    //Ticket styles
    ticketWrapper: {
        marginRight: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: COLORS.CATPURPDRK,
        overflow: 'hidden',
    },
    ticketContainer: {
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: '#000000',
        borderBottomWidth: 2,
    },
    ticketImage: {
        overflow: 'hidden',
        alignSelf: 'center',
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        justifyContent: 'flex-end',
    },
    ticketFooter: {
        padding: 10,
        backgroundColor: COLORS.BLACK,
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 7.3,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: COLORS.AKCRUBACKGROUND,
        borderTopWidth: 2,
        overflow: 'hidden',
    },
    linearGradient: {
        height: '70%',
    },
    ticketCircle: {
        height: 20,
        width: 20,
        borderRadius: 20,
        backgroundColor: COLORS.AKCRUBACKGROUND,
    },
    mitMovieCard: {
        flexDirection: 'row',
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    mitMovieCardContent: {
        flex: 1,
        marginLeft: 10,
        minWidth: 0,
    },
    countdownContainer: {
        marginTop: 0,
        alignItems: 'center',
        marginBottom: 12,
        backgroundColor: 'transparent',
        borderRadius: 22,
        borderWidth: 0,
        borderColor: 'transparent',
        marginHorizontal: 5,
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowRadius: 0,
        shadowOffset: {width: 0, height: 0},
        elevation: 10,
    },
    countdownContainerSticky: {
        marginTop: 0,
        marginBottom: 4,
    },
    receiveTopCompact: {
        marginTop: 0,
    },
    pendingBackRow: {
        width: '96%',
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    pendingBackRowCompact: {
        marginBottom: 4,
    },
    pendingBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
    },
    pendingBackText: {
        ...FONTS.Title3,
        color: COLORS.LIGHTGREY,
        marginLeft: 3,
    },
    pendingWaitingText: {
        ...FONTS.Title3,
        color: COLORS.AKCRUBLUE,
        marginLeft: 10,
        textAlign: 'left',
    },
    countdownRingWrap: {
        width: COUNTDOWN_RING_SIZE,
        height: COUNTDOWN_RING_SIZE,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        marginTop: 22,
    },
    countdownRingWrapCompact: {
        marginTop: 2,
    },
    countdownOuterGlow: {
        position: 'absolute',
        width: COUNTDOWN_GLOW_SIZE,
        height: COUNTDOWN_GLOW_SIZE,
        borderRadius: COUNTDOWN_GLOW_SIZE / 2,
        backgroundColor: 'rgba(151, 98, 255, 0.2)',
        shadowColor: '#B678FF',
        shadowOpacity: 0.7,
        shadowRadius: 28,
        shadowOffset: {width: 0, height: 0},
        elevation: 12,
    },
    countdownRingOuter: {
        width: COUNTDOWN_RING_SIZE,
        height: COUNTDOWN_RING_SIZE,
        borderRadius: COUNTDOWN_RING_RADIUS,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.09)',
        padding: 2,
        overflow: 'hidden',
        position: 'relative',
    },
    countdownRingSpin: {
        position: 'absolute',
        top: COUNTDOWN_RING_THICKNESS,
        left: COUNTDOWN_RING_THICKNESS,
        right: COUNTDOWN_RING_THICKNESS,
        bottom: COUNTDOWN_RING_THICKNESS,
        borderRadius: COUNTDOWN_SPIN_RADIUS,
    },
    countdownRingInnerContent: {
        width: '100%',
        height: '100%',
        borderRadius: COUNTDOWN_SPIN_RADIUS,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 3,
        zIndex: 1,
        backgroundColor: 'transparent',
    },
    countdownDialCenter: {
        width: '101%',
        height: '101%',
        borderRadius: COUNTDOWN_RING_RADIUS,
        backgroundColor: 'rgba(10, 4, 20, 0.94)',
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
        paddingBottom: 12,
        paddingHorizontal: 10,
    },
    countdownTitleInCircle: {
        ...FONTS.paragraph1,
        color: '#D4C2F5',
        marginBottom: 8,
        letterSpacing: 0.6,
    },
    countdownHRule: {
        width: '88%',
        alignSelf: 'center',
        height: StyleSheet.hairlineWidth,
        backgroundColor: 'rgba(200, 175, 255, 0.45)',
        marginTop: 10,
        marginBottom: 8,
    },
    countdownTimerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 0,
        width: '100%',
    },
    countdownUnit: {
        alignItems: 'center',
        marginHorizontal: 1,
    },
    countdownDigitsRow: {
        flexDirection: 'row',
    },
    countdownDigitBox: {
        width: 30,
        height: 48,
        borderRadius: 8,
        backgroundColor: 'rgba(24,20,36,0.95)',
        borderWidth: 1,
        borderColor: 'rgba(174,146,255,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 1,
    },
    countdownDigitText: {
        ...FONTS.Title1,
        color: COLORS.WHITE,
    },
    countdownSeparator: {
        ...FONTS.Title1,
        color: '#F0D0FF',
        marginHorizontal: 3,
    },
    countdownSubTextInCircle: {
        ...FONTS.paragraph2,
        color: '#C9B8E6',
        textAlign: 'center',
        marginTop: 0,
        lineHeight: 20,
        fontSize: 12,
    },
    inviteInfoCard: {
        width: '100%',
        borderRadius: MIT_COMBINED_CARD_RADIUS,
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'rgba(0, 0, 0, 0.72)',
        paddingHorizontal: 8,
        paddingVertical: 0,
        height: MIT_COMBINED_CARD_HEIGHT,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inviteInfoCardBorder: {
        width: '96%',
        alignSelf: 'center',
        marginTop: 30,
        borderRadius: MIT_COMBINED_CARD_RADIUS,
        padding: 1,
        shadowColor: '#C97BFF',
        shadowOpacity: 0.55,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: 0},
        elevation: 10,
    },
    inviteAvatarWrap: {
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    inviteInfoBody: {
        flex: 1,
        minWidth: 0,
        paddingRight: 8,
    },
    inviteInfoUsername: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginBottom: 2,
    },
    inviteInfoMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    inviteInfoMetaText: {
        ...FONTS.paragraph2,
        color: 'rgba(255,255,255,0.88)',
        marginLeft: 6,
    },
    inviteInfoStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
    },
    inviteInfoStatusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#4FE1FF',
        marginRight: 6,
        alignSelf: 'center',
    },
    inviteInfoStatusText: {
        ...FONTS.Title2,
        color: '#EFE0FF',
        includeFontPadding: false,
        textAlignVertical: 'center',
    },
    inviteFollowerWrap: {
        minWidth: 76,
        alignItems: 'center',
        justifyContent: 'center',
        borderLeftWidth: 1,
        borderLeftColor: 'rgba(255,255,255,0.2)',
        paddingLeft: 8,
    },
    inviteFollowerCount: {
        ...FONTS.Title2,
        color: COLORS.AKCRUBLUE,
    },
    inviteFollowerLabel: {
        ...FONTS.paragraph2,
        color: 'rgba(187, 224, 255, 0.95)',
        marginTop: 1,
    },
    inviteMovieCard: {
        width: '100%',
        borderRadius: MIT_COMBINED_CARD_RADIUS,
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'rgba(0, 0, 0, 0.72)',
        paddingHorizontal: 8,
        paddingVertical: 10,
        height: MIT_COMBINED_CARD_HEIGHT,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inviteMovieCardBorder: {
        width: '96%',
        marginTop: 20,
        borderRadius: 16,
        padding: 1,
        shadowColor: '#C97BFF',
        shadowOpacity: 0.48,
        shadowRadius: 11,
        shadowOffset: {width: 0, height: 0},
        elevation: 9,
    },
    inviteMoviePoster: {
        width: 58,
        height: 78,
        borderRadius: 8,
        marginRight: 10,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    inviteMovieInfo: {
        flex: 1,
        minWidth: 0,
        paddingRight: 8,
    },
    inviteTrailerWrap: {
        minWidth: 76,
        borderLeftWidth: 1,
        borderLeftColor: 'rgba(255,255,255,0.2)',
        paddingLeft: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    inviteTrailerGradient: {
        borderRadius: 10,
        padding: 1,
    },
    inviteMovieTitle: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    inviteMovieMeta: {
        ...FONTS.paragraph2,
        color: 'rgba(236,220,255,0.9)',
        marginTop: 3,
    },
    inviteMovieTagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: 6,
    },
    inviteMovieTag: {
        ...FONTS.paragraph2,
        color: '#1A0C2A',
        backgroundColor: '#DDB3FF',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 10,
        marginRight: 6,
        marginBottom: 4,
    },
    inviteTrailerSideButton: {
        borderRadius: 10,
        backgroundColor: 'rgba(20, 10, 34, 0.9)',
        paddingHorizontal: 8,
        minHeight: 52,
        paddingVertical: 8,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
    inviteTrailerIcon: {
        marginBottom: 2,
    },
    inviteTrailerButtonText: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        textAlign: 'center',
    },
    pendingActionsWrap: {
        marginTop: 12,
        alignItems: 'center',
        width: '100%',
    },
    mitSwipeWrap: {
        paddingTop: 12,
        width: '96%',
        alignSelf: 'center',
    },
    pendingSwipeBottomArea: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
    },
    pendingPinnedSharedBg: {
        backgroundColor: 'rgba(8, 2, 18, 0.92)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(177, 145, 255, 0.35)',
    },
    pendingSentPinnedContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: '4%',
        paddingTop: 8,
        zIndex: 20,
    },
    pendingSwipeHintText: {
        ...FONTS.Title2,
        color: COLORS.PINK,
        textAlign: 'center',
        paddingTop: 10,
    },
    cancelInviteButton: {
        width: SIZES.ScreenWidth * 0.9,
        marginTop: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FF6B7D',
        backgroundColor: 'rgba(255, 86, 105, 0.22)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    cancelInviteIcon: {
        marginRight: 6,
    },
    cancelInviteButtonText: {
        ...FONTS.Title1,
        color: '#FFD8DE',
    },
    secondaryActionButton: {
        width: SIZES.ScreenWidth * 0.9,
        marginTop: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#B08BFF',
        backgroundColor: 'rgba(120, 83, 255, 0.24)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    secondaryActionIcon: {
        marginRight: 6,
    },
    secondaryActionText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    backToFeedText: {
        ...FONTS.Title2,
        color: '#E7D9FF',
        textDecorationLine: 'underline',
        marginTop: 14,
        marginBottom: 2,
    },
    acceptedScreenContainer: {
        flex: 1,
        backgroundColor: '#080212',
    },
    acceptedScreenGlow: {
        ...StyleSheet.absoluteFillObject,
    },
    acceptedScreenScrollContent: {
        flexGrow: 1,
        paddingBottom: 24,
    },
    acceptedShell: {
        width: '92%',
        alignSelf: 'center',
        marginTop: 8,
        paddingBottom: 14,
    },
    declinedRecoveryWrap: {
        width: '100%',
        alignSelf: 'center',
        marginTop: 2,
        paddingBottom: 10,
    },
    declinedPinnedContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        alignItems: 'center',
        zIndex: 25,
    },
    declinedPinnedActionsWrap: {
        width: '92%',
        alignSelf: 'center',
    },
    declinedHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    declinedHeaderTitle: {
        ...FONTS.ContentTitle,
        color: '#F1E6FF',
        marginLeft: 8,
        fontSize: 22,
        textAlign: 'center',
    },
    declinedHeaderSubtitle: {
        ...FONTS.paragraph1,
        color: '#D7C9F2',
        textAlign: 'center',
        marginTop: 6,
        marginBottom: 12,
    },
    declinedSecondaryActionButton: {
        minHeight: 58,
        borderRadius: 13,
        borderWidth: 1,
        borderColor: 'rgba(179, 153, 255, 0.5)',
        backgroundColor: 'rgba(44, 27, 88, 0.86)',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 10,
    },
    declinedActionIcon: {
        marginRight: 8,
    },
    declinedActionBody: {
        flex: 1,
        minWidth: 0,
    },
    declinedActionTitle: {
        ...FONTS.Title2,
        color: '#FFFFFF',
    },
    declinedActionSubtitle: {
        ...FONTS.paragraph2,
        color: '#DCCFFF',
        marginTop: 2,
    },
    declinedUpsellBorder: {
        borderRadius: 14,
        padding: 1,
        marginBottom: 10,
    },
    declinedUpsellCard: {
        borderRadius: 13,
        borderWidth: 1,
        borderColor: 'rgba(255, 217, 160, 0.44)',
        backgroundColor: 'rgba(38, 22, 52, 0.92)',
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    declinedUpsellHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    declinedUpsellTitle: {
        ...FONTS.Title2,
        color: '#FFE5B7',
        marginLeft: 7,
    },
    declinedUpsellSubtitle: {
        ...FONTS.paragraph2,
        color: '#F5E2CC',
        marginTop: 6,
        marginBottom: 10,
    },
    declinedUpsellCta: {
        height: 36,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(196, 185, 255, 0.5)',
        backgroundColor: 'rgba(88, 72, 247, 0.88)',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        paddingHorizontal: 20,
    },
    declinedUpsellCtaText: {
        ...FONTS.Title2,
        color: '#FFFFFF',
    },
    declinedFooterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
        marginBottom: 2,
    },
    declinedFooterLine: {
        width: 68,
        height: 1,
        backgroundColor: 'rgba(215, 192, 255, 0.35)',
    },
    declinedFooterText: {
        ...FONTS.paragraph2,
        color: '#DCCFFF',
        marginHorizontal: 10,
    },
    acceptedDustOrb: {
        position: 'absolute',
        borderRadius: 999,
        backgroundColor: 'rgba(241, 125, 255, 0.28)',
    },
    acceptedDustOrbTop: {
        width: 180,
        height: 180,
        top: 90,
        right: -60,
    },
    acceptedDustOrbMid: {
        width: 140,
        height: 140,
        top: 300,
        left: -55,
        backgroundColor: 'rgba(111, 219, 255, 0.24)',
    },
    acceptedDustOrbBottom: {
        width: 120,
        height: 120,
        bottom: 80,
        right: 5,
        backgroundColor: 'rgba(183, 108, 255, 0.24)',
    },
    acceptedTicketIconWrap: {
        width: 120,
        height: 78,
        borderRadius: 12,
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 4,
    },
    acceptedTicketImage: {
        width: 110,
        height: 70,
    },
    acceptedHeading: {
        ...FONTS.ContentTitle,
        color: '#FFFFFF',
        textAlign: 'center',
        marginTop: 12,
    },
    acceptedSubtitle: {
        ...FONTS.paragraph1,
        color: '#E7D9FF',
        textAlign: 'center',
        marginTop: 6,
        lineHeight: 20,
        width: '92%',
        alignSelf: 'center',
    },
    sharedInviteCardBorder: {
        width: '100%',
        marginTop: 18,
        borderRadius: 16,
        padding: 1,
        shadowColor: '#C97BFF',
        shadowOpacity: 0.5,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: 0},
        elevation: 8,
    },
    sharedInviteCard: {
        borderRadius: 15,
        padding: 10,
        backgroundColor: 'rgba(7, 6, 20, 0.78)',
        borderWidth: 1,
        borderColor: 'rgba(201, 141, 255, 0.36)',
    },
    sharedUserRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sharedAvatarWrap: {
        marginRight: 10,
    },
    sharedUserBody: {
        flex: 1,
        minWidth: 0,
    },
    sharedFollowerCountWrap: {
        minWidth: 56,
        marginLeft: 10,
        paddingLeft: 10,
        borderLeftWidth: 1,
        borderLeftColor: 'rgba(187, 156, 255, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sharedFollowerCountValue: {
        ...FONTS.Title2,
        color: '#A7E9FF',
    },
    sharedFollowerCountLabel: {
        ...FONTS.paragraph2,
        color: '#D6CAFF',
        marginTop: 2,
    },
    sharedInviteUsername: {
        ...FONTS.Title2,
        color: '#FFFFFF',
        marginBottom: 2,
    },
    sharedMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    sharedMetaText: {
        ...FONTS.paragraph2,
        color: '#EADFFF',
        marginLeft: 6,
    },
    sharedMovieDivider: {
        height: 1,
        backgroundColor: 'rgba(187, 156, 255, 0.4)',
        marginVertical: 10,
    },
    sharedMovieRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sharedMoviePoster: {
        width: 58,
        height: 78,
        borderRadius: 8,
        marginRight: 10,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    sharedMovieBody: {
        flex: 1,
        minWidth: 0,
    },
    sharedMovieActionWrap: {
        minWidth: 74,
        marginLeft: 10,
        paddingLeft: 10,
        borderLeftWidth: 1,
        borderLeftColor: 'rgba(187, 156, 255, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sharedMovieTitle: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    sharedMovieMeta: {
        ...FONTS.paragraph2,
        color: 'rgba(236,220,255,0.9)',
        marginTop: 3,
    },
    sharedMovieTagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: 6,
    },
    sharedMovieTrailerButton: {
        alignSelf: 'center',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(174, 125, 255, 0.75)',
        backgroundColor: 'rgba(76, 25, 130, 0.55)',
        borderRadius: 8,
        paddingHorizontal: 6,
        paddingVertical: 6,
    },
    sharedMovieTrailerButtonText: {
        ...FONTS.paragraph2,
        color: COLORS.WHITE,
        marginTop: 2,
        textAlign: 'center',
    },
    acceptedInviteCardBorder: {
        marginTop: 16,
        borderRadius: 16,
        padding: 1,
    },
    acceptedInviteCard: {
        borderRadius: 15,
        padding: 10,
        backgroundColor: 'rgba(7, 6, 20, 0.78)',
        borderWidth: 1,
        borderColor: 'rgba(201, 141, 255, 0.36)',
        flexDirection: 'row',
        alignItems: 'center',
    },
    acceptedAvatar: {
        width: 62,
        height: 62,
        borderRadius: 12,
        marginRight: 10,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    acceptedInviteCardBody: {
        flex: 1,
    },
    acceptedInviteUsername: {
        ...FONTS.Title2,
        color: '#FFFFFF',
        marginBottom: 2,
    },
    acceptedMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    acceptedMetaText: {
        ...FONTS.paragraph2,
        color: '#EADFFF',
        marginLeft: 6,
    },
    acceptedConfirmedRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    acceptedConfirmedText: {
        ...FONTS.Title3,
        color: '#9BFFD3',
        marginLeft: 6,
    },
    acceptedOpenChatButtonGlow: {
        marginTop: 14,
        borderRadius: 14,
        padding: 1,
    },
    acceptedOpenChatButton: {
        height: 50,
        borderRadius: 13,
        backgroundColor: 'rgba(44, 13, 87, 0.85)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.32)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    acceptedOpenChatText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginLeft: 8,
    },
    acceptedHintText: {
        ...FONTS.paragraph2,
        color: '#EEDFFF',
        textAlign: 'center',
        marginTop: 7,
    },
    acceptedPromptSection: {
        marginTop: 20,
    },
    acceptedPromptTitle: {
        ...FONTS.Title2,
        color: '#F4E9FF',
        textAlign: 'center',
        marginBottom: 10,
    },
    acceptedPromptChip: {
        borderWidth: 1,
        borderColor: 'rgba(200, 138, 255, 0.7)',
        backgroundColor: 'rgba(58, 15, 107, 0.55)',
        borderRadius: 10,
        paddingVertical: 9,
        paddingHorizontal: 12,
        marginBottom: 8,
    },
    acceptedPromptChipText: {
        ...FONTS.paragraph2,
        color: '#FFFFFF',
    },
    acceptedComposerWrap: {
        marginTop: 14,
    },
    acceptedComposerPinnedContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: '4%',
        paddingTop: 8,
        backgroundColor: 'rgba(8, 2, 18, 0.92)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(177, 145, 255, 0.35)',
    },
    acceptedComposerHeader: {
        marginBottom: 8,
    },
    acceptedComposerHeaderText: {
        ...FONTS.paragraph2,
        color: '#D7C5FF',
    },

});
