import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

export default StyleSheet.create({
    hiddenSection: {
        display: 'none',
    },
    topcontainer: {
        marginTop: 46,
        marginHorizontal: 15,
    },
    bottomcontainer: {
        marginHorizontal: 15,
        marginTop: -10,
    },
    poster: {width: 85, height: 115, borderRadius: 5},
    datebox: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.BLACK,
        borderRadius: 5,
        padding: 15,
    },
    datetext: {
        ...FONTS.Title2,
        color: COLORS.LIGHTGREY,
    },
    inviteStatusRow: {
        ...FONTS.Title2,
        textAlign: 'center',
        marginTop: 8,
        letterSpacing: 0.5,
    },
    inviteStatusPrefix: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    inviteStatusValue: {
        ...FONTS.Title2,
        color: COLORS.STARGOLD,
    },
    inviteStatusSubtext: {
        ...FONTS.paragraph1,
        color: COLORS.WHITE,
        textAlign: 'center',
        marginTop: 4,
        paddingHorizontal: 12,
    },
    sheetcontainer: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    screenGlowBackground: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 0,
    },
    chooseMitScroll: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitScrollContent: {
        paddingBottom: 16,
        flexGrow: 1,
        backgroundColor: COLORS.BLACK,
    },
    pendingScreenContainer: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    pendingScreenScrollContent: {
        flexGrow: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitBottomBar: {
        backgroundColor: 'transparent',
        paddingTop: 0,
        position: 'absolute',
        top: 70,
        left: 0,
        right: 0,
        zIndex: 20,
    },
    swipeSectionRaised: {
        marginTop: 0,
    },
    sheetview: {},
    opensheet: {
        height: SIZES.ScreenHeight * 0.2,
        backgroundColor: COLORS.TAGCOLOR,
        padding: 10,
    },
    input: {
        flexDirection: 'row',
        borderWidth: 0.8,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        justifyContent: 'space-between',
        marginVertical: 10,
        paddingLeft: 10,
        alignContent: 'center',
        height: 40,
        alignItems: 'center',
    },
    textinput: {
        color: COLORS.LIGHTGREY,
        width: '100%',
        flex: 1,
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    playButton: {
        ...FONTS.Title2,
    },
    activitycontainer: {
        height: SIZES.ScreenHeight,
        width: SIZES.ScreenWidth,
        justifyContent: 'center',
    },
    postcontainer: {
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        marginBottom: 5,
    },
    //Ticket styles
    ticketWrapper: {
        marginRight: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: COLORS.CATPURPDRK,
        overflow: 'hidden',
    },
    ticketContainer: {
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: '#000000',
        borderBottomWidth: 2,
    },
    ticketImage: {
        overflow: 'hidden',
        alignSelf: 'center',
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        justifyContent: 'flex-end',
    },
    ticketFooter: {
        padding: 10,
        backgroundColor: COLORS.BLACK,
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 7.3,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: COLORS.AKCRUBACKGROUND,
        borderTopWidth: 2,
        overflow: 'hidden',
    },
    linearGradient: {
        height: '70%',
    },
    ticketCircle: {
        height: 20,
        width: 20,
        borderRadius: 20,
        backgroundColor: COLORS.AKCRUBACKGROUND,
    },
    mitMovieCard: {
        flexDirection: 'row',
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    mitMovieCardContent: {
        flex: 1,
        marginLeft: 10,
        minWidth: 0,
    },
    countdownContainer: {
        marginTop: 0,
        alignItems: 'center',
        marginBottom: 12,
        backgroundColor: 'transparent',
        borderRadius: 22,
        borderWidth: 0,
        borderColor: 'transparent',
        marginHorizontal: 5,
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowRadius: 0,
        shadowOffset: {width: 0, height: 0},
        elevation: 10,
    },
    countdownContainerSticky: {
        marginTop: 0,
        marginBottom: 4,
    },
    receiveTopCompact: {
        marginTop: 0,
    },
    pendingBackRow: {
        width: '96%',
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    pendingBackRowCompact: {
        marginBottom: 4,
    },
    pendingBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
    },
    pendingBackText: {
        ...FONTS.Title3,
        color: COLORS.LIGHTGREY,
        marginLeft: 3,
    },
    pendingWaitingText: {
        ...FONTS.Title3,
        color: COLORS.AKCRUBLUE,
        marginLeft: 10,
        textAlign: 'left',
    },
    countdownRingWrap: {
        width: 265,
        height: 265,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        marginTop: 10,
    },
    countdownRingWrapCompact: {
        marginTop: 2,
    },
    countdownOuterGlow: {
        position: 'absolute',
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: 'rgba(151, 98, 255, 0.2)',
        shadowColor: '#B678FF',
        shadowOpacity: 0.7,
        shadowRadius: 28,
        shadowOffset: {width: 0, height: 0},
        elevation: 12,
    },
    countdownRingOuter: {
        width: 265,
        height: 265,
        borderRadius: 132.5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.09)',
        padding: 2,
        overflow: 'hidden',
        position: 'relative',
    },
    countdownRingSpin: {
        position: 'absolute',
        top: 2,
        left: 2,
        right: 2,
        bottom: 2,
        borderRadius: 130.5,
    },
    countdownRingInnerContent: {
        width: '100%',
        height: '100%',
        borderRadius: 130.5,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 3,
        zIndex: 1,
        backgroundColor: 'transparent',
    },
    countdownDialCenter: {
        width: '97%',
        height: '97%',
        borderRadius: 130,
        backgroundColor: 'rgba(10, 4, 20, 0.94)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
        paddingBottom: 12,
        paddingHorizontal: 10,
    },
    countdownTitleInCircle: {
        ...FONTS.paragraph1,
        color: '#D4C2F5',
        marginBottom: 8,
        letterSpacing: 0.6,
    },
    countdownHRule: {
        width: '88%',
        alignSelf: 'center',
        height: StyleSheet.hairlineWidth,
        backgroundColor: 'rgba(200, 175, 255, 0.45)',
        marginTop: 10,
        marginBottom: 8,
    },
    countdownTimerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 0,
        width: '100%',
    },
    countdownUnit: {
        alignItems: 'center',
        marginHorizontal: 1,
    },
    countdownDigitsRow: {
        flexDirection: 'row',
    },
    countdownDigitBox: {
        width: 30,
        height: 48,
        borderRadius: 8,
        backgroundColor: 'rgba(24,20,36,0.95)',
        borderWidth: 1,
        borderColor: 'rgba(174,146,255,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 1,
    },
    countdownDigitText: {
        ...FONTS.Title1,
        color: COLORS.WHITE,
    },
    countdownSeparator: {
        ...FONTS.Title1,
        color: '#F0D0FF',
        marginHorizontal: 3,
    },
    countdownSubTextInCircle: {
        ...FONTS.paragraph2,
        color: '#C9B8E6',
        textAlign: 'center',
        marginTop: 0,
        lineHeight: 20,
        fontSize: 12,
    },
    inviteInfoCard: {
        width: '100%',
        borderRadius: 16,
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'rgba(0, 0, 0, 0.72)',
        paddingHorizontal: 8,
        paddingVertical: 0,
        height: 120,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inviteInfoCardBorder: {
        width: '96%',
        marginTop: 30,
        borderRadius: 16,
        padding: 1,
        shadowColor: '#C97BFF',
        shadowOpacity: 0.55,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: 0},
        elevation: 10,
    },
    inviteAvatarWrap: {
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    inviteInfoBody: {
        flex: 1,
        minWidth: 0,
    },
    inviteInfoUsername: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
        marginBottom: 2,
    },
    inviteInfoMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    inviteInfoMetaText: {
        ...FONTS.paragraph2,
        color: 'rgba(255,255,255,0.88)',
        marginLeft: 6,
    },
    inviteInfoStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
    },
    inviteInfoStatusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#4FE1FF',
        marginRight: 6,
    },
    inviteInfoStatusText: {
        ...FONTS.Title2,
        color: '#EFE0FF',
    },
    inviteMovieCard: {
        width: '100%',
        borderRadius: 16,
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'rgba(0, 0, 0, 0.72)',
        paddingHorizontal: 8,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inviteMovieCardBorder: {
        width: '96%',
        marginTop: 20,
        borderRadius: 16,
        padding: 1,
        shadowColor: '#C97BFF',
        shadowOpacity: 0.48,
        shadowRadius: 11,
        shadowOffset: {width: 0, height: 0},
        elevation: 9,
    },
    inviteMoviePoster: {
        width: 58,
        height: 78,
        borderRadius: 8,
        marginRight: 10,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    inviteMovieInfo: {
        flex: 1,
        minWidth: 0,
    },
    inviteMovieTitle: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    inviteMovieMeta: {
        ...FONTS.paragraph2,
        color: 'rgba(236,220,255,0.9)',
        marginTop: 3,
    },
    inviteMovieTagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: 6,
    },
    inviteMovieTag: {
        ...FONTS.paragraph2,
        color: '#1A0C2A',
        backgroundColor: '#DDB3FF',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 10,
        marginRight: 6,
        marginBottom: 4,
    },
    pendingActionsWrap: {
        marginTop: 12,
        alignItems: 'center',
        width: '100%',
    },
    mitSwipeWrap: {
        paddingTop: 12,
        width: '100%',
    },
    pendingSwipeBottomArea: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
    },
    pendingSwipeHintText: {
        ...FONTS.Title2,
        color: COLORS.PINK,
        textAlign: 'center',
        paddingTop: 10,
    },
    cancelInviteButton: {
        width: SIZES.ScreenWidth * 0.9,
        marginTop: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FF6B7D',
        backgroundColor: 'rgba(255, 86, 105, 0.22)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    cancelInviteIcon: {
        marginRight: 6,
    },
    cancelInviteButtonText: {
        ...FONTS.Title1,
        color: '#FFD8DE',
    },
    secondaryActionButton: {
        width: SIZES.ScreenWidth * 0.9,
        marginTop: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#B08BFF',
        backgroundColor: 'rgba(120, 83, 255, 0.24)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    secondaryActionIcon: {
        marginRight: 6,
    },
    secondaryActionText: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    backToFeedText: {
        ...FONTS.Title2,
        color: '#E7D9FF',
        textDecorationLine: 'underline',
        marginTop: 14,
        marginBottom: 2,
    },
});
