import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

export default StyleSheet.create({
    topcontainer: {
        marginTop: 46,
        marginHorizontal: 15,
    },
    bottomcontainer: {
        marginHorizontal: 15,
        marginTop: -10,
    },
    poster: {width: 85, height: 115, borderRadius: 5},
    datebox: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.BLACK,
        borderRadius: 5,
        padding: 15,
    },
    datetext: {
        ...FONTS.Title2,
        color: COLORS.LIGHTGREY,
    },
    inviteStatusRow: {
        ...FONTS.Title2,
        textAlign: 'center',
        marginTop: 8,
        letterSpacing: 0.5,
    },
    inviteStatusPrefix: {
        ...FONTS.Title2,
        color: COLORS.WHITE,
    },
    inviteStatusValue: {
        ...FONTS.Title2,
        color: COLORS.STARGOLD,
    },
    inviteStatusSubtext: {
        ...FONTS.paragraph1,
        color: COLORS.WHITE,
        textAlign: 'center',
        marginTop: 4,
        paddingHorizontal: 12,
    },
    sheetcontainer: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitScroll: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitScrollContent: {
        paddingBottom: 16,
        flexGrow: 1,
        backgroundColor: COLORS.BLACK,
    },
    chooseMitBottomBar: {
        backgroundColor: COLORS.BLACK,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.12)',
        paddingTop: 8,
    },
    sheetview: {},
    opensheet: {
        height: SIZES.ScreenHeight * 0.2,
        backgroundColor: COLORS.TAGCOLOR,
        padding: 10,
    },
    input: {
        flexDirection: 'row',
        borderWidth: 0.8,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        justifyContent: 'space-between',
        marginVertical: 10,
        paddingLeft: 10,
        alignContent: 'center',
        height: 40,
        alignItems: 'center',
    },
    textinput: {
        color: COLORS.LIGHTGREY,
        width: '100%',
        flex: 1,
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    playButton: {
        ...FONTS.Title2,
    },
    activitycontainer: {
        height: SIZES.ScreenHeight,
        width: SIZES.ScreenWidth,
        justifyContent: 'center',
    },
    postcontainer: {
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        marginBottom: 5,
    },
    //Ticket styles
    ticketWrapper: {
        marginRight: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: COLORS.CATPURPDRK,
        overflow: 'hidden',
    },
    ticketContainer: {
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: '#000000',
        borderBottomWidth: 2,
    },
    ticketImage: {
        overflow: 'hidden',
        alignSelf: 'center',
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 2.7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        justifyContent: 'flex-end',
    },
    ticketFooter: {
        padding: 10,
        backgroundColor: COLORS.BLACK,
        width: SIZES.ScreenWidth / 2.75,
        height: SIZES.ScreenWidth / 7.3,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderStyle: 'dashed',
        borderColor: COLORS.AKCRUBACKGROUND,
        borderTopWidth: 2,
        overflow: 'hidden',
    },
    linearGradient: {
        height: '70%',
    },
    ticketCircle: {
        height: 20,
        width: 20,
        borderRadius: 20,
        backgroundColor: COLORS.AKCRUBACKGROUND,
    },
    mitMovieCard: {
        flexDirection: 'row',
        width: SIZES.ScreenWidth * 0.93,
        alignSelf: 'center',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    mitMovieCardContent: {
        flex: 1,
        marginLeft: 10,
        minWidth: 0,
    },
    countdownContainer: {
        marginTop: 25,
        alignItems: 'center',
        marginBottom: 12,
        backgroundColor: '#111214',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 0,
        marginHorizontal: 5,
    },
    countdownContainerSticky: {
        marginTop: 4,
        marginBottom: 4,
    },
    countdownTitle: {
        ...FONTS.Title1,
        color: COLORS.WHITE,
        marginBottom: 12,
    },
    countdownTimerRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'center',
        marginBottom: 15,
        width: '100%',
    },
    countdownUnit: {
        alignItems: 'center',
        marginHorizontal: 4,
    },
    countdownDigitsRow: {
        flexDirection: 'row',
    },
    countdownDigitBox: {
        width: 36,
        height: 54,
        borderRadius: 10,
        backgroundColor: '#1f2328',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 2,
    },
    countdownDigitText: {
        ...FONTS.H1,
        color: COLORS.WHITE,
    },
    countdownUnitLabel: {
        ...FONTS.paragraph2,
        color: COLORS.STARGOLD,
        marginTop: 8,
        letterSpacing: 1,
    },
    countdownMidLine: {
        width: 74,
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.15)',
        marginTop: -27,
        marginBottom: 26,
    },
});
