import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#050508',
    },
    scrollContent: {
        paddingBottom: 120,
    },
    headerContainer: {
        zIndex: 100,
    },
    gradientWrapper: {
        height: SIZES.ScreenHeight * 0.15,
        marginTop: -68,
        backgroundColor: '#050508',
    },
    gradientWrapperTablet: {
        marginTop: -160,
    },
    gradient: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: SIZES.ScreenHeight * 0.15,
    },
    gradientTablet: {
        height: SIZES.ScreenHeight * 0.26,
    },
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: '20%',
        marginHorizontal: 15,
    },
    cancelText: {
        ...FONTS.Title3,
        marginLeft: 5,
    },
    contentContainer: {
        marginTop: '5%',
        marginHorizontal: 15,
        backgroundColor: '#121722',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.OVERLAY_WHITE_08,
        padding: 12,
    },
    profileRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarContainer: {
        marginRight: 8,
    },
    authorMeta: {
        flexShrink: 1,
    },
    usernameText: {
        ...FONTS.Title2,
        fontSize: 12,
    },
    inlineBadge: {
        marginTop: 4,
        flexShrink: 0,
        transform: [{scale: 0.92}],
    },
    input: {
        width: SIZES.ScreenWidth * 0.87,
        borderWidth: 1,
        borderRadius: 10,
        borderColor: COLORS.FADEDBLACK,
        marginTop: 10,
        alignSelf: 'center',
        minHeight: 120,
        backgroundColor: '#0b1019',
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    textinput: {
        ...FONTS.paragraph1,
        color: COLORS.LIGHTGREY,
        minHeight: 100,
        textAlignVertical: 'top',
    },
    inputAreaWrap: {
        position: 'relative',
        zIndex: 50,
    },
    charCount: {
        ...FONTS.paragraph3,
        color: COLORS.OVERLAY_WHITE_45,
        alignSelf: 'flex-end',
        marginTop: 6,
    },
    suggestionPanel: {
        position: 'absolute',
        top: 126,
        left: 0,
        right: 0,
        backgroundColor: '#0b1019',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.OVERLAY_WHITE_08,
        maxHeight: 260,
        overflow: 'hidden',
        zIndex: 100,
        elevation: 8,
    },
    suggestionList: {
        width: '100%',
    },
    mentionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 9,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.OVERLAY_WHITE_05,
        backgroundColor: COLORS.OVERLAY_WHITE_02,
    },
    mentionMeta: {
        marginLeft: 10,
        flex: 1,
    },
    mentionNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    mentionUsername: {
        ...FONTS.Title2,
        fontSize: 13,
        color: COLORS.WHITE,
    },
    mentionFirstName: {
        ...FONTS.paragraph1,
        color: COLORS.OVERLAY_WHITE_65,
        marginLeft: 8,
    },
    mentionBadgeWrap: {
        marginTop: 4,
        alignSelf: 'flex-start',
    },
    mediaActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },
    mediaIconButton: {
        marginHorizontal: 10,
    },
    mediaIconButtonVideo: {
        marginHorizontal: 8,
    },
    mediaPreviewContainer: {
        marginTop: 10,
    },
    previewItemWrap: {
        position: 'relative',
    },
    selectedImage: {
        width: SIZES.ScreenWidth / 3.8,
        height: SIZES.ScreenWidth / 2.5,
        margin: 5,
        borderRadius: 8,
    },
    removeMediaButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: 'rgba(255, 0, 0, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    removeVideoButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: 'rgba(255, 0, 0, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    cancelButton: {
        ...FONTS.paragraph1,
        backgroundColor: COLORS.AKCRUPINK,
        paddingHorizontal: 5,
        paddingVertical: 5,
        borderRadius: 5,
    },
    searchinput: {
        width: SIZES.ScreenWidth / 1.08,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginVertical: 10,
        alignItems: 'center',
        height: 35,
    },
    bottomActionBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 16,
        backgroundColor: '#050508',
        borderTopWidth: 1,
        borderTopColor: COLORS.FADEDBLACK,
    },
    postvideo: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 10,
        marginTop: 10,
        overflow: 'hidden',
    },
    video: {
        width: '100%',
        height: '100%',
        borderRadius: 10,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: COLORS.OVERLAY_BLACK_50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sizeModalCard: {
        backgroundColor: COLORS.AKCRUBACKGROUND,
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
        marginHorizontal: 15,
    },
    sizeModalText: {
        ...FONTS.Title3,
        marginBottom: 10,
        textAlign: 'center',
    },
    sizeModalClose: {
        ...FONTS.Title2,
        marginBottom: 10,
        textAlign: 'center',
        color: COLORS.MIDORANGE,
    },
    loadingOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.OVERLAY_BLACK_50,
    },
});
