import { StyleSheet, Platform } from "react-native";
import { COLORS, SIZES, FONTS } from "../../../../assets/constants";

export default StyleSheet.create({
    input: {
        flexDirection: 'row',
        borderWidth: 0.8,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        justifyContent: 'space-between',
        marginVertical: 10,
        paddingLeft: 10,
        alignItems: 'flex-start',
        height: 150,
    },
    textinput: {
        color: COLORS.LIGHTGREY,
    },
    sendbutton: {
        backgroundColor: COLORS.AKCRUBLUE,
        height: 35,
        justifyContent: 'center',
        width: 90,
        borderRadius: 5,
        alignItems: 'center',
    },
    topcontainer: {
        marginHorizontal: 15,
        backgroundColor: COLORS.AKCRUBACKGROUND,
    },
    screenTitle: {
        ...FONTS.Title3,
        marginTop: 10,
        marginBottom: 10,
        marginRight: 10,
    },
    choosedate: {
        ...FONTS.Title3,
        marginTop: 10,
        marginBottom: 10,
        marginRight: 10,
        textAlign: 'center',
        textDecorationLine: 'underline',
    },
    drawfonttag: {
        ...FONTS.Title2Orange,
        color: COLORS.BLACK,
        backgroundColor: COLORS.STARGOLD,
        paddingHorizontal: 4,
        paddingVertical: 1,
        marginHorizontal: 2,
        borderRadius: 4,
        textAlign: 'center',
    },
    //Starting Picker Styles
    container: {
        marginHorizontal: 15,
    },
    monthContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    monthText: {
        ...FONTS.Title3,
        marginHorizontal: 10,
        color: COLORS.AKCRUBLUE,
    },
    arrowButton: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    arrowbuttonstyle: {
        color: COLORS.WHITE,
        fontSize: 18,
    },
    datePickerContainer: {
        flexDirection: 'row',
        marginTop: 10,
        marginBottom: 10,
    },
    dayButton: {
        width: 60,
        height: 60,
        borderRadius: 5,
        backgroundColor: COLORS.TAGCOLOR,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 5,
    },
    dayButtonSelected: {
        backgroundColor: COLORS.AKCRUBLUE,
    },
    dayText: {
        ...FONTS.Title2,
    },
    dayTextSelected: {
        color: 'white',
    },
    dayOfWeekText: {
        ...FONTS.Title2,
        marginTop: 5,
    },
    timePickerContainer: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    timeButton: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 5,
        backgroundColor: COLORS.TAGCOLOR,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 5,
    },
    timeButtonSelected: {
        backgroundColor: COLORS.AKCRUBLUE,
    },
    timeText: {
        ...FONTS.Title2,
    },
    timeTextSelected: {
        color: 'white',
    },
    timeZonePickerContainer: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    timeZoneButton: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 5,
        backgroundColor: COLORS.TAGCOLOR,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 5,
    },
    timeZoneButtonSelected: {
        backgroundColor: COLORS.AKCRUBLUE,
    },
    timeZoneText: {
        ...FONTS.Title2,
    },
    timeZoneTextSelected: {
        color: 'white',
    },
    selectedDateTimeContainer: {
        marginTop: 20,
        marginBottom: 10,
    },
    selectedDateTimeText: {
        ...FONTS.Title2,
        marginBottom: 5,
    },
    disabledButton: {
        opacity: 0.5,
    },
    searchmodal: {
        backgroundColor: COLORS.AKCRUBACKGROUND,
        alignItems: 'center',
    },
    searchinput: {
        width: SIZES.ScreenWidth / 1.1,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginVertical: 10,
        alignItems: 'center',
        height: 40,
    },
    icon: {
        marginRight: 5,
    },
    activitycontainer: {
        height: SIZES.ScreenHeight,
        width: SIZES.ScreenWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    backbutton: {
        backgroundColor: COLORS.AKCRUBACKGROUND,
        marginTop: Platform.OS === 'ios' ? '10%' : 0,
    },
    ticketContainer: {
        width: SIZES.ScreenWidth / 1.4,
        height: SIZES.ScreenWidth / 1,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderStyle: 'dashed',
        borderColor: '#000000',
        borderBottomWidth: 2,
    },
    ticketImage: {
        overflow: 'hidden',
        alignSelf: 'center',
        width: SIZES.ScreenWidth / 1.4,
        height: SIZES.ScreenWidth / 1,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        justifyContent: 'flex-end',
    },
    ticketFooter: {
        padding: 10,
        backgroundColor: COLORS.AKCRUBLUE,
        width: SIZES.ScreenWidth / 1.4,
        height: SIZES.ScreenWidth / 2.5,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        borderStyle: 'dashed',
        borderColor: COLORS.AKCRUBACKGROUND,
        borderTopWidth: 2,
        overflow: 'hidden',
    },
    linearGradient: {
        height: '70%',
    },
    ticketCircle: {
        height: 80,
        width: 80,
        borderRadius: 80,
        backgroundColor: COLORS.AKCRUBACKGROUND,
    },
    mitSearchRoot: {
        width: '100%',
        backgroundColor: COLORS.BLACK,
    },
    mitSearchTopGradient: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: 65,
        width: SIZES.ScreenWidth,
    },
    mitSearchLauncherWrap: {
        alignItems: 'center',
        backgroundColor: COLORS.BLACK,
    },
    mitSearchLauncher: {
        width: SIZES.ScreenWidth / 1.1,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 10,
        paddingHorizontal: 12,
        marginVertical: 10,
        alignItems: 'center',
        height: 46,
        backgroundColor: 'rgba(255,255,255,0.03)',
    },
    mitSearchLauncherIcon: {
        marginRight: 10,
    },
    mitSearchLauncherText: {
        ...FONTS.Title2,
        color: COLORS.DARKGREY,
    },
    mitModalRoot: {
        backgroundColor: COLORS.BLACK,
        flex: 1,
    },
    mitModalTopRow: {
        paddingHorizontal: 10,
        paddingTop: Platform.OS === 'ios' ? 4 : 8,
        paddingBottom: 6,
        backgroundColor: COLORS.BLACK,
    },
    mitBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingHorizontal: 6,
        paddingVertical: 6,
    },
    mitBackButtonText: {
        ...FONTS.Title3,
        marginLeft: 4,
    },
    mitSearchModalBody: {
        paddingHorizontal: 16,
        paddingBottom: 8,
        backgroundColor: COLORS.BLACK,
    },
    mitSearchInput: {
        width: '100%',
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 10,
        paddingHorizontal: 10,
        alignItems: 'center',
        height: 46,
        backgroundColor: 'rgba(255,255,255,0.03)',
    },
    mitSearchIcon: {
        marginRight: 8,
    },
    mitSearchInputText: {
        color: COLORS.LIGHTGREY,
        flex: 1,
        ...FONTS.Title2,
    },
    mitSearchClearButton: {
        width: 22,
        height: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mitSearchHint: {
        ...FONTS.paragraph1,
        color: COLORS.DARKGREY,
        marginTop: 8,
        marginLeft: 2,
    },
    mitMovieListWrap: {
        flex: 1,
        paddingHorizontal: 10,
        paddingTop: 4,
        backgroundColor: COLORS.BLACK,
    },
    mitMovieRow: {
        marginHorizontal: 6,
        marginBottom: 10,
        paddingVertical: 12,
        paddingHorizontal: 10,
        minHeight: 84,
        backgroundColor: 'rgba(255,255,255,0.02)',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
        flexDirection: 'row',
        alignItems: 'center',
    },
    mitMoviePoster: {
        width: 70,
        height: 70,
        borderRadius: 4,
        backgroundColor: COLORS.BLACK,
    },
    mitMovieMeta: {
        flex: 1,
        marginLeft: 10,
        marginRight: 8,
    },
    mitMovieTitle: {
        ...FONTS.Title2,
        fontSize: 13,
    },
    mitMovieYear: {
        ...FONTS.paragraph1,
        fontSize: 12,
        color: COLORS.DARKGREY,
        marginTop: 2,
    },
    mitMovieChipRow: {
        marginTop: 5,
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 6,
    },
    mitMovieChip: {
        ...FONTS.paragraph6,
        color: COLORS.WHITE,
        backgroundColor: 'rgba(183, 149, 255, 0.35)',
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 10,
        overflow: 'hidden',
    },
    mitLoaderWrap: {
        paddingTop: 26,
        alignItems: 'center',
    },
    mitEmptyWrap: {
        paddingTop: 28,
        alignItems: 'center',
    },
    mitEmptyText: {
        ...FONTS.paragraph1,
        color: COLORS.DARKGREY,
    },
    mitViewContainer: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    mitViewScrollContent: {
        paddingBottom: 90,
        backgroundColor: COLORS.BLACK,
    },
    mitViewTopSection: {
        paddingBottom: 4,
        backgroundColor: COLORS.BLACK,
    },
    mitViewBackWrap: {
        marginHorizontal: 15,
    },
    mitViewSelectedUserRow: {
        marginTop: 8,
        marginBottom: 4,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mitViewSelectedUserCard: {
        flex: 1,
    },
    mitViewGenresSection: {
        marginTop: 8,
        marginBottom: 8,
        backgroundColor: COLORS.BLACK,
    },
    mitViewGenreTitle: {
        ...FONTS.Title2,
        marginHorizontal: SIZES.marginhorizontal,
        marginVertical: SIZES.marginvertical,
    },
    mitViewGenresWrap: {
        alignItems: 'center',
        width: SIZES.ScreenWidth,
        alignSelf: 'center',
    },
});
