import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../../../assets/constants';
import {isTablet} from '../../../../assets/constants/theme';

export default StyleSheet.create({
    scrollContent: {
        paddingBottom: 140,
    },
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.BLACK,
    },
    headerZIndex: {
        zIndex: 100,
    },
    cancelRowStandalone: {
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 0,
        backgroundColor: COLORS.BLACK,
    },
    cancelText: {
        ...FONTS.Title3,
        color: COLORS.WHITE,
    },
    composerWrap: {
        marginTop: 8,
        marginHorizontal: 15,
        backgroundColor: COLORS.BLACK,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.FADEDBLACK,
        padding: 12,
    },
    authorRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarWrap: {
        marginRight: 8,
    },
    authorMeta: {
        flexShrink: 1,
    },
    usernameBadgeRow: {
        marginTop: 8,
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
    },
    usernameText: {
        ...FONTS.Title1,
        flexShrink: 1,
        minWidth: 0,
        marginBottom: 4,
        textAlign: 'left',
    },
    inlineBadge: {
        flexShrink: 0,
    },
    input: {
        width: SIZES.ScreenWidth * 0.92,
        borderColor: COLORS.LIGHTGREY,
        marginTop: 10,
        alignSelf: 'center',
        minHeight: SIZES.ScreenHeight * 0.14,
        backgroundColor: COLORS.BLACK,
        borderRadius: 10,
        borderWidth: 1,
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    textinput: {
        ...FONTS.paragraph1,
        color: COLORS.LIGHTGREY,
    },
    inputAreaWrap: {
        position: 'relative',
        zIndex: 50,
    },
    suggestionPanel: {
        position: 'absolute',
        top: 126,
        left: 0,
        right: 0,
        backgroundColor: '#0b1019',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        maxHeight: 260,
        overflow: 'hidden',
        zIndex: 100,
        elevation: 8,
    },
    suggestionList: {
        width: '100%',
    },
    mentionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 9,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
        backgroundColor: 'rgba(255,255,255,0.02)',
    },
    mentionMeta: {
        marginLeft: 10,
        flex: 1,
    },
    mentionNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    mentionUsername: {
        ...FONTS.Title2,
        fontSize: 13,
        color: COLORS.WHITE,
    },
    mentionFirstName: {
        ...FONTS.paragraph1,
        color: 'rgba(255,255,255,0.65)',
        marginLeft: 8,
    },
    mentionBadgeWrap: {
        marginTop: 4,
        alignSelf: 'flex-start',
    },
    uploadMediaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 8,
        width: SIZES.ScreenWidth - 32,
        alignSelf: 'center',
        borderWidth: 0,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: 'transparent',
    },
    uploadDivider: {
        marginTop: 10,
        marginBottom: 4,
        width: SIZES.ScreenWidth - 32,
        alignSelf: 'center',
    },
    uploadMediaButton: {
        borderWidth: 1,
        borderColor: COLORS.AKCRUBLUE,
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(23,37,84,0.35)',
    },
    commentSwitchLabel: {
        ...FONTS.Title3,
        color: COLORS.WHITE,
    },
    mediaPreviewWrap: {
        marginTop: 10,
        width: SIZES.ScreenWidth - 32,
        alignSelf: 'center',
    },
    previewImage: {
        width: SIZES.ScreenWidth / 2.9,
        height: SIZES.ScreenWidth / 1.9,
        margin: 5,
        borderRadius: 8,
    },
    previewImageCard: {
        position: 'relative',
    },
    removeMediaButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: 'rgba(255, 0, 0, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    removeVideoButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 0, 0, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 3,
    },
    limitCard: {
        marginHorizontal: 10,
        marginTop: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.FADEDBLACK,
        padding: 8,
        backgroundColor: COLORS.BLACK,
    },
    limitText: {
        ...FONTS.paragraph1,
        color: COLORS.DARKGREY,
        textAlign: 'center',
    },
    choicesContainer: {
        marginTop: 12,
        width: SIZES.ScreenWidth - 32,
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: COLORS.FADEDBLACK,
        borderRadius: 10,
        padding: 10,
    },
    choice: {
        borderWidth: 1,
        borderColor: COLORS.DARKGREY,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 8,
        marginBottom: 8,
    },
    choiceInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    choiceInput: {
        flex: 1,
        ...FONTS.paragraph1,
        color: COLORS.WHITE,
    },
    choiceImage: {
        width: 40,
        height: 40,
        borderRadius: 5,
        marginTop: 8,
    },
    choiceButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    addChoiceButton: {
        marginTop: 10,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    addChoiceButtonText: {
        ...FONTS.Title2,
        color: COLORS.PINK,
        marginRight: 5,
    },
    durationContainer: {
        marginTop: 2,
        alignItems: 'center',
        width: SIZES.ScreenWidth - 32,
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: COLORS.FADEDBLACK,
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 10,
    },
    durationLabel: {
        ...FONTS.Title2,
        color: COLORS.PINK,
        marginBottom: 8,
    },
    durationInputs: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
    },
    durationInput: {
        ...FONTS.paragraph1,
        borderWidth: 1,
        borderColor: COLORS.PINK,
        borderRadius: 5,
        paddingHorizontal: 10,
        width: isTablet() ? '35%' : '40%',
        height: isTablet() ? 60 : 40,
        color: COLORS.WHITE,
    },
    durationSeparator: {
        ...FONTS.Title3,
        color: COLORS.PINK,
        marginHorizontal: 10,
    },
    durationHint: {
        ...FONTS.paragraph1,
        textAlign: 'center',
        color: COLORS.DARKGREY,
        marginTop: 8,
    },
    bottomPostBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 16,
        backgroundColor: COLORS.BLACK,
        borderTopWidth: 1,
        borderTopColor: COLORS.FADEDBLACK,
    },
    bottomPostButton: {
        width: '100%',
    },
    postvideo: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 10,
        marginTop: 10,
        overflow: 'hidden',
        position: 'relative',
    },
    loadingOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    cancelButton: {
        ...FONTS.paragraph1,
        backgroundColor: COLORS.AKCRUPINK,
        paddingHorizontal: 5,
        paddingVertical: 5,
        borderRadius: 5,
    },
});
